//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Invicta.Net.SisoRef010.CodeGeneration.Xml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6", IsNullable=false)]
    public partial class ebv {
        
        private object copyrightField;
        
        private revisions_t revisionsField;
        
        private generictable_t[] itemsField;
        
        private string titleField;
        
        private string releaseField;
        
        private string hrefField;
        
        private System.DateTime dateField;
        
        private string descriptionField;
        
        private string organisationField;
        
        /// <remarks/>
        public object copyright {
            get {
                return this.copyrightField;
            }
            set {
                this.copyrightField = value;
            }
        }
        
        /// <remarks/>
        public revisions_t revisions {
            get {
                return this.revisionsField;
            }
            set {
                this.revisionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bitfield", typeof(bitfield_t))]
        [System.Xml.Serialization.XmlElementAttribute("cet", typeof(cet_t))]
        [System.Xml.Serialization.XmlElementAttribute("cot", typeof(cot_t))]
        [System.Xml.Serialization.XmlElementAttribute("dict", typeof(dict_t))]
        [System.Xml.Serialization.XmlElementAttribute("enum", typeof(enum_t))]
        [System.Xml.Serialization.XmlElementAttribute("jammer_technique", typeof(jammer_technique_t))]
        [System.Xml.Serialization.XmlElementAttribute("record", typeof(record_t))]
        public generictable_t[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string release {
            get {
                return this.releaseField;
            }
            set {
                this.releaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string organisation {
            get {
                return this.organisationField;
            }
            set {
                this.organisationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class datatype_t {
        
        private object[] itemsField;
        
        private string nameField;
        
        private string typeField;
        
        private genericentrytext_tStatus statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cr", typeof(cr_t))]
        [System.Xml.Serialization.XmlElementAttribute("cr_range", typeof(cr_range_t))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public genericentrytext_tStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class cr_t {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class cr_range_t {
        
        private string value_minField;
        
        private string value_maxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string value_min {
            get {
                return this.value_minField;
            }
            set {
                this.value_minField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string value_max {
            get {
                return this.value_maxField;
            }
            set {
                this.value_maxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public enum genericentrytext_tStatus {
        
        /// <remarks/>
        pending,
        
        /// <remarks/>
        @new,
        
        /// <remarks/>
        hold,
        
        /// <remarks/>
        working,
        
        /// <remarks/>
        future,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class field_t {
        
        private object[] itemsField;
        
        private datatype_t[] datatypeField;
        
        private string nameField;
        
        private genericentrytext_tStatus statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cr", typeof(cr_t))]
        [System.Xml.Serialization.XmlElementAttribute("cr_range", typeof(cr_range_t))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("datatype")]
        public datatype_t[] datatype {
            get {
                return this.datatypeField;
            }
            set {
                this.datatypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public genericentrytext_tStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class col_t {
        
        private string keyField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class meta_t {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(entity_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(genericentryxref_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(subcategory_xref_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(genericentryrange_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(subcategory_range_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(extra_range_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(specific_range_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(category_range_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(enumrow_range_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(genericentrysingle_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(jammer_specific_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(jammer_subcategory_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(jammer_category_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(jammer_kind_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(extra_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(specific_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(subcategory_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(category_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(enumrow_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(genericentrystring_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(genericentrydescription_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(bitfieldrow_t))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public abstract partial class genericentry_t {
        
        private object[] itemsField;
        
        private string footnoteField;
        
        private bool deprecatedField;
        
        private bool deprecatedFieldSpecified;
        
        private bool retiredField;
        
        private bool retiredFieldSpecified;
        
        private genericentrytext_tStatus statusField;
        
        private bool statusFieldSpecified;
        
        private bool draft1278Field;
        
        private bool draft1278FieldSpecified;
        
        private string uuidField;
        
        private string baseuuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cr", typeof(cr_t))]
        [System.Xml.Serialization.XmlElementAttribute("cr_range", typeof(cr_range_t))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string footnote {
            get {
                return this.footnoteField;
            }
            set {
                this.footnoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool deprecated {
            get {
                return this.deprecatedField;
            }
            set {
                this.deprecatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deprecatedSpecified {
            get {
                return this.deprecatedFieldSpecified;
            }
            set {
                this.deprecatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool retired {
            get {
                return this.retiredField;
            }
            set {
                this.retiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retiredSpecified {
            get {
                return this.retiredFieldSpecified;
            }
            set {
                this.retiredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public genericentrytext_tStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool draft1278 {
            get {
                return this.draft1278Field;
            }
            set {
                this.draft1278Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool draft1278Specified {
            get {
                return this.draft1278FieldSpecified;
            }
            set {
                this.draft1278FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string baseuuid {
            get {
                return this.baseuuidField;
            }
            set {
                this.baseuuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class object_t : genericentry_t {
        
        private genericentry_t[] items1Field;
        
        private string domainField;
        
        private string kindField;
        
        private string uidField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("category", typeof(category_t))]
        [System.Xml.Serialization.XmlElementAttribute("category_range", typeof(category_range_t))]
        public genericentry_t[] Items1 {
            get {
                return this.items1Field;
            }
            set {
                this.items1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string kind {
            get {
                return this.kindField;
            }
            set {
                this.kindField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class category_t : genericentrysingle_t {
        
        private genericentry_t[] items1Field;
        
        private bool transferredField;
        
        private bool transferredFieldSpecified;
        
        private bool variationField;
        
        private bool variationFieldSpecified;
        
        private string uidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subcategory", typeof(subcategory_t))]
        [System.Xml.Serialization.XmlElementAttribute("subcategory_range", typeof(subcategory_range_t))]
        [System.Xml.Serialization.XmlElementAttribute("subcategory_xref", typeof(subcategory_xref_t))]
        public genericentry_t[] Items1 {
            get {
                return this.items1Field;
            }
            set {
                this.items1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool transferred {
            get {
                return this.transferredField;
            }
            set {
                this.transferredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transferredSpecified {
            get {
                return this.transferredFieldSpecified;
            }
            set {
                this.transferredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool variation {
            get {
                return this.variationField;
            }
            set {
                this.variationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool variationSpecified {
            get {
                return this.variationFieldSpecified;
            }
            set {
                this.variationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class subcategory_t : genericentrysingle_t {
        
        private genericentry_t[] items1Field;
        
        private bool transferredField;
        
        private bool transferredFieldSpecified;
        
        private bool variationField;
        
        private bool variationFieldSpecified;
        
        private string uidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("specific", typeof(specific_t))]
        [System.Xml.Serialization.XmlElementAttribute("specific_range", typeof(specific_range_t))]
        public genericentry_t[] Items1 {
            get {
                return this.items1Field;
            }
            set {
                this.items1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool transferred {
            get {
                return this.transferredField;
            }
            set {
                this.transferredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transferredSpecified {
            get {
                return this.transferredFieldSpecified;
            }
            set {
                this.transferredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool variation {
            get {
                return this.variationField;
            }
            set {
                this.variationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool variationSpecified {
            get {
                return this.variationFieldSpecified;
            }
            set {
                this.variationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class specific_t : genericentrysingle_t {
        
        private genericentry_t[] items1Field;
        
        private bool transferredField;
        
        private bool transferredFieldSpecified;
        
        private bool variationField;
        
        private bool variationFieldSpecified;
        
        private string uidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("extra", typeof(extra_t))]
        [System.Xml.Serialization.XmlElementAttribute("extra_range", typeof(extra_range_t))]
        public genericentry_t[] Items1 {
            get {
                return this.items1Field;
            }
            set {
                this.items1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool transferred {
            get {
                return this.transferredField;
            }
            set {
                this.transferredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transferredSpecified {
            get {
                return this.transferredFieldSpecified;
            }
            set {
                this.transferredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool variation {
            get {
                return this.variationField;
            }
            set {
                this.variationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool variationSpecified {
            get {
                return this.variationFieldSpecified;
            }
            set {
                this.variationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class extra_t : genericentrysingle_t {
        
        private bool transferredField;
        
        private bool transferredFieldSpecified;
        
        private bool variationField;
        
        private bool variationFieldSpecified;
        
        private string uidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool transferred {
            get {
                return this.transferredField;
            }
            set {
                this.transferredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transferredSpecified {
            get {
                return this.transferredFieldSpecified;
            }
            set {
                this.transferredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool variation {
            get {
                return this.variationField;
            }
            set {
                this.variationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool variationSpecified {
            get {
                return this.variationFieldSpecified;
            }
            set {
                this.variationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(jammer_specific_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(jammer_subcategory_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(jammer_category_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(jammer_kind_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(extra_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(specific_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(subcategory_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(category_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(enumrow_t))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public abstract partial class genericentrysingle_t : genericentry_t {
        
        private string descriptionField;
        
        private string xrefField;
        
        private uint groupField;
        
        private bool groupFieldSpecified;
        
        private uint valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string xref {
            get {
                return this.xrefField;
            }
            set {
                this.xrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool groupSpecified {
            get {
                return this.groupFieldSpecified;
            }
            set {
                this.groupFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class jammer_specific_t : genericentrysingle_t {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class jammer_subcategory_t : genericentrysingle_t {
        
        private jammer_specific_t[] jammer_specificField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("jammer_specific")]
        public jammer_specific_t[] jammer_specific {
            get {
                return this.jammer_specificField;
            }
            set {
                this.jammer_specificField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class jammer_category_t : genericentrysingle_t {
        
        private jammer_subcategory_t[] jammer_subcategoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("jammer_subcategory")]
        public jammer_subcategory_t[] jammer_subcategory {
            get {
                return this.jammer_subcategoryField;
            }
            set {
                this.jammer_subcategoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class jammer_kind_t : genericentrysingle_t {
        
        private jammer_category_t[] jammer_categoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("jammer_category")]
        public jammer_category_t[] jammer_category {
            get {
                return this.jammer_categoryField;
            }
            set {
                this.jammer_categoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class enumrow_t : genericentrysingle_t {
        
        private meta_t[] metaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("meta")]
        public meta_t[] meta {
            get {
                return this.metaField;
            }
            set {
                this.metaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class extra_range_t : genericentryrange_t {
        
        private bool transferredField;
        
        private bool transferredFieldSpecified;
        
        private bool variationField;
        
        private bool variationFieldSpecified;
        
        private string uidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool transferred {
            get {
                return this.transferredField;
            }
            set {
                this.transferredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transferredSpecified {
            get {
                return this.transferredFieldSpecified;
            }
            set {
                this.transferredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool variation {
            get {
                return this.variationField;
            }
            set {
                this.variationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool variationSpecified {
            get {
                return this.variationFieldSpecified;
            }
            set {
                this.variationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(subcategory_range_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(extra_range_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(specific_range_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(category_range_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(enumrow_range_t))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public abstract partial class genericentryrange_t : genericentry_t {
        
        private string descriptionField;
        
        private string xrefField;
        
        private uint groupField;
        
        private bool groupFieldSpecified;
        
        private uint value_minField;
        
        private uint value_maxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string xref {
            get {
                return this.xrefField;
            }
            set {
                this.xrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool groupSpecified {
            get {
                return this.groupFieldSpecified;
            }
            set {
                this.groupFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint value_min {
            get {
                return this.value_minField;
            }
            set {
                this.value_minField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint value_max {
            get {
                return this.value_maxField;
            }
            set {
                this.value_maxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class subcategory_range_t : genericentryrange_t {
        
        private genericentry_t[] items1Field;
        
        private bool transferredField;
        
        private bool transferredFieldSpecified;
        
        private bool variationField;
        
        private bool variationFieldSpecified;
        
        private string uidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("specific", typeof(specific_t))]
        [System.Xml.Serialization.XmlElementAttribute("specific_range", typeof(specific_range_t))]
        public genericentry_t[] Items1 {
            get {
                return this.items1Field;
            }
            set {
                this.items1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool transferred {
            get {
                return this.transferredField;
            }
            set {
                this.transferredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transferredSpecified {
            get {
                return this.transferredFieldSpecified;
            }
            set {
                this.transferredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool variation {
            get {
                return this.variationField;
            }
            set {
                this.variationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool variationSpecified {
            get {
                return this.variationFieldSpecified;
            }
            set {
                this.variationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class specific_range_t : genericentryrange_t {
        
        private genericentry_t[] items1Field;
        
        private bool transferredField;
        
        private bool transferredFieldSpecified;
        
        private bool variationField;
        
        private bool variationFieldSpecified;
        
        private string uidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("extra", typeof(extra_t))]
        [System.Xml.Serialization.XmlElementAttribute("extra_range", typeof(extra_range_t))]
        public genericentry_t[] Items1 {
            get {
                return this.items1Field;
            }
            set {
                this.items1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool transferred {
            get {
                return this.transferredField;
            }
            set {
                this.transferredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transferredSpecified {
            get {
                return this.transferredFieldSpecified;
            }
            set {
                this.transferredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool variation {
            get {
                return this.variationField;
            }
            set {
                this.variationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool variationSpecified {
            get {
                return this.variationFieldSpecified;
            }
            set {
                this.variationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class category_range_t : genericentryrange_t {
        
        private genericentry_t[] items1Field;
        
        private bool transferredField;
        
        private bool transferredFieldSpecified;
        
        private bool variationField;
        
        private bool variationFieldSpecified;
        
        private string uidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subcategory", typeof(subcategory_t))]
        [System.Xml.Serialization.XmlElementAttribute("subcategory_range", typeof(subcategory_range_t))]
        [System.Xml.Serialization.XmlElementAttribute("subcategory_xref", typeof(subcategory_xref_t))]
        public genericentry_t[] Items1 {
            get {
                return this.items1Field;
            }
            set {
                this.items1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool transferred {
            get {
                return this.transferredField;
            }
            set {
                this.transferredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transferredSpecified {
            get {
                return this.transferredFieldSpecified;
            }
            set {
                this.transferredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool variation {
            get {
                return this.variationField;
            }
            set {
                this.variationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool variationSpecified {
            get {
                return this.variationFieldSpecified;
            }
            set {
                this.variationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class subcategory_xref_t : genericentryxref_t {
        
        private genericentry_t[] items1Field;
        
        private bool transferredField;
        
        private bool transferredFieldSpecified;
        
        private bool variationField;
        
        private bool variationFieldSpecified;
        
        private string uidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("specific", typeof(specific_t))]
        [System.Xml.Serialization.XmlElementAttribute("specific_range", typeof(specific_range_t))]
        public genericentry_t[] Items1 {
            get {
                return this.items1Field;
            }
            set {
                this.items1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool transferred {
            get {
                return this.transferredField;
            }
            set {
                this.transferredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transferredSpecified {
            get {
                return this.transferredFieldSpecified;
            }
            set {
                this.transferredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool variation {
            get {
                return this.variationField;
            }
            set {
                this.variationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool variationSpecified {
            get {
                return this.variationFieldSpecified;
            }
            set {
                this.variationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(subcategory_xref_t))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public abstract partial class genericentryxref_t : genericentry_t {
        
        private string descriptionField;
        
        private string xrefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string xref {
            get {
                return this.xrefField;
            }
            set {
                this.xrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class enumrow_range_t : genericentryrange_t {
        
        private meta_t[] metaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("meta")]
        public meta_t[] meta {
            get {
                return this.metaField;
            }
            set {
                this.metaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class entity_t : genericentry_t {
        
        private genericentry_t[] items1Field;
        
        private string kindField;
        
        private string domainField;
        
        private string countryField;
        
        private string uidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("category", typeof(category_t))]
        [System.Xml.Serialization.XmlElementAttribute("category_range", typeof(category_range_t))]
        public genericentry_t[] Items1 {
            get {
                return this.items1Field;
            }
            set {
                this.items1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string kind {
            get {
                return this.kindField;
            }
            set {
                this.kindField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class genericentrystring_t : genericentry_t {
        
        private string descriptionField;
        
        private string xrefField;
        
        private uint groupField;
        
        private bool groupFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string xref {
            get {
                return this.xrefField;
            }
            set {
                this.xrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool groupSpecified {
            get {
                return this.groupFieldSpecified;
            }
            set {
                this.groupFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(bitfieldrow_t))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class genericentrydescription_t : genericentry_t {
        
        private string descriptionField;
        
        private string xrefField;
        
        private uint groupField;
        
        private bool groupFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string xref {
            get {
                return this.xrefField;
            }
            set {
                this.xrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool groupSpecified {
            get {
                return this.groupFieldSpecified;
            }
            set {
                this.groupFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class bitfieldrow_t : genericentrydescription_t {
        
        private string nameField;
        
        private uint bit_positionField;
        
        private string lengthField;
        
        public bitfieldrow_t() {
            this.lengthField = "1";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint bit_position {
            get {
                return this.bit_positionField;
            }
            set {
                this.bit_positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        [System.ComponentModel.DefaultValueAttribute("1")]
        public string length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class revision_t {
        
        private object[] itemsField;
        
        private string titleField;
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private string uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cr", typeof(cr_t))]
        [System.Xml.Serialization.XmlElementAttribute("cr_range", typeof(cr_range_t))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(jammer_technique_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(record_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cot_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cet_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(bitfield_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(enum_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(dict_t))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(revisions_t))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public abstract partial class generictable_t {
        
        private genericentrytext_t[] descriptionField;
        
        private object[] itemsField;
        
        private string uidField;
        
        private string nameField;
        
        private genericentrytext_tStatus statusField;
        
        private bool statusFieldSpecified;
        
        private bool draft1278Field;
        
        private bool draft1278FieldSpecified;
        
        private bool deprecatedField;
        
        private bool deprecatedFieldSpecified;
        
        private uint groupField;
        
        private bool groupFieldSpecified;
        
        private string footnoteField;
        
        private string applicabilityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("description")]
        public genericentrytext_t[] description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cr", typeof(cr_t))]
        [System.Xml.Serialization.XmlElementAttribute("cr_range", typeof(cr_range_t))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public genericentrytext_tStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool draft1278 {
            get {
                return this.draft1278Field;
            }
            set {
                this.draft1278Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool draft1278Specified {
            get {
                return this.draft1278FieldSpecified;
            }
            set {
                this.draft1278FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool deprecated {
            get {
                return this.deprecatedField;
            }
            set {
                this.deprecatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deprecatedSpecified {
            get {
                return this.deprecatedFieldSpecified;
            }
            set {
                this.deprecatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool groupSpecified {
            get {
                return this.groupFieldSpecified;
            }
            set {
                this.groupFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string footnote {
            get {
                return this.footnoteField;
            }
            set {
                this.footnoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string applicability {
            get {
                return this.applicabilityField;
            }
            set {
                this.applicabilityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class genericentrytext_t {
        
        private object[] itemsField;
        
        private string[] textField;
        
        private string footnoteField;
        
        private genericentrytext_tStatus statusField;
        
        private bool statusFieldSpecified;
        
        private string uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cr", typeof(cr_t))]
        [System.Xml.Serialization.XmlElementAttribute("cr_range", typeof(cr_range_t))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string footnote {
            get {
                return this.footnoteField;
            }
            set {
                this.footnoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public genericentrytext_tStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class jammer_technique_t : generictable_t {
        
        private jammer_kind_t[] jammer_kindField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("jammer_kind")]
        public jammer_kind_t[] jammer_kind {
            get {
                return this.jammer_kindField;
            }
            set {
                this.jammer_kindField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class record_t : generictable_t {
        
        private field_t[] fieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("field")]
        public field_t[] field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class cot_t : generictable_t {
        
        private object_t[] objectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("object")]
        public object_t[] @object {
            get {
                return this.objectField;
            }
            set {
                this.objectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class cet_t : generictable_t {
        
        private entity_t[] entityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entity")]
        public entity_t[] entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class bitfield_t : generictable_t {
        
        private bitfieldrow_t[] bitfieldrowField;
        
        private string sizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bitfieldrow")]
        public bitfieldrow_t[] bitfieldrow {
            get {
                return this.bitfieldrowField;
            }
            set {
                this.bitfieldrowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class enum_t : generictable_t {
        
        private col_t[][] headerField;
        
        private genericentry_t[] items1Field;
        
        private string sizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("col", typeof(col_t[]), IsNullable=false)]
        public col_t[][] header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("enumrow", typeof(enumrow_t))]
        [System.Xml.Serialization.XmlElementAttribute("enumrow_range", typeof(enumrow_range_t))]
        public genericentry_t[] Items1 {
            get {
                return this.items1Field;
            }
            set {
                this.items1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class dict_t : generictable_t {
        
        private genericentrystring_t[] dictrowField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dictrow")]
        public genericentrystring_t[] dictrow {
            get {
                return this.dictrowField;
            }
            set {
                this.dictrowField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sisostds.org/schemas/SISO-REF-010/2.6")]
    public partial class revisions_t : generictable_t {
        
        private revision_t[] revisionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("revision")]
        public revision_t[] revision {
            get {
                return this.revisionField;
            }
            set {
                this.revisionField = value;
            }
        }
    }
}
