//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(204, "Aggregate State-Aggregate State", 8)]
	public enum AggregateStateAggregateState : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b0b22e2-526a-11df-8216-080069138b88", Description="Other")]
		Other = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b0c3268-526a-11df-8be5-080069138b88", Description="Aggregated")]
		Aggregated = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b0d3d70-526a-11df-bc6c-080069138b88", Description="Disaggregated")]
		Disaggregated = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b0e4e40-526a-11df-be32-080069138b88", Description="Fully disaggregated")]
		FullyDisaggregated = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b0f5ea2-526a-11df-900c-080069138b88", Description="Pseudo-disaggregated")]
		PseudoDisaggregated = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b106f86-526a-11df-a3ef-080069138b88", Description="Partially-disaggregated")]
		PartiallyDisaggregated = 5,
	}
}
