//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(130, "Animal Lifeform Group Size Range Enumeration for all Domains", 8)]
	public enum AnimalLifeformGroupSizeRangeEnumerationForAllDomains : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d0b72385-8945-4ae6-a489-38660d8abc88", Description="Number of animals range from 201 to 249")]
		NumberOfAnimalsRangeFrom201To249 = 201,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("61a9ee8e-890c-4b22-beb4-edcf609d5dbf", Description="Number of animals range from 250 to 299")]
		NumberOfAnimalsRangeFrom250To299 = 202,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("334bfadc-560c-4317-9797-c62a31480d72", Description="Number of animals range from 300 to 399")]
		NumberOfAnimalsRangeFrom300To399 = 203,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("75ff2746-ec6a-4c39-a191-f7690d58017f", Description="Number of animals range from 400 to 499")]
		NumberOfAnimalsRangeFrom400To499 = 204,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("005eb268-d414-4a80-a476-2524ac00dc12", Description="Number of animals range from 500 to 999")]
		NumberOfAnimalsRangeFrom500To999 = 205,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("2beaba42-7aec-49a1-8b44-a2b9f99b833a", Description="Number of animals range from 1,000 to 1,499")]
		NumberOfAnimalsRangeFrom1000To1499 = 206,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("7a716f82-c4dd-4068-b989-7155d4d1e997", Description="Number of animals range from 1,500 to 1,999")]
		NumberOfAnimalsRangeFrom1500To1999 = 207,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("805db2c8-1b6d-4fe4-a634-ec135df6e215", Description="Number of animals range from 2,000 to 2,999")]
		NumberOfAnimalsRangeFrom2000To2999 = 208,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("8dc48fb8-6e16-4eb6-b3ff-427bfb55868e", Description="Number of animals range from 3,000 to 4,999")]
		NumberOfAnimalsRangeFrom3000To4999 = 210,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e9d362e0-257c-4ef0-ac56-faefa2cbb95b", Description="Number of animals range from 5,000 to 6,999")]
		NumberOfAnimalsRangeFrom5000To6999 = 212,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("cddafa1e-6150-400b-81d5-f344ee8173b4", Description="Number of animals range from 7,000 to 9,999")]
		NumberOfAnimalsRangeFrom7000To9999 = 214,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c6543d69-3391-4f53-9b61-3b3a1e4964e4", Description="Number of animals range from 10,000 to 19,999")]
		NumberOfAnimalsRangeFrom10000To19999 = 216,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("714494dd-64b9-4f2b-8e4e-718f695ec8d4", Description="Number of animals range from 20,000 to 50,000")]
		NumberOfAnimalsRangeFrom20000To50000 = 218,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("98bb5d5a-524a-452f-9622-5c746f0c270c", Description="Number of animals range greater than 50,000")]
		NumberOfAnimalsRangeGreaterThan50000 = 220,
	}
}
