//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(395, "Appearance-Environmental Density", 4)]
	public enum AppearanceEnvironmentalDensity : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("02ea72ee-526a-11df-91e1-080069138b88", Description="Clear")]
		Clear = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("02eb7fea-526a-11df-bc50-080069138b88", Description="Hazy")]
		Hazy = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("02ec8e9e-526a-11df-a549-080069138b88", Description="Dense")]
		Dense = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("02ed978a-526a-11df-8f26-080069138b88", Description="Very Dense")]
		VeryDense = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("02eea422-526a-11df-ae94-080069138b88", Description="Opaque")]
		Opaque = 4,
	}
}
