//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(400, "Appearance-NVG Mode", 1)]
	public enum AppearanceNVGMode : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9f919ecf-e1d2-412a-84b3-435f272f95fa", Description="Overt Lighting")]
		OvertLighting = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("91db8045-e4eb-4c51-905f-d77d69874eb6", Description="Covert Lighting (Night Vision Goggles)")]
		CovertLightingNightVisionGoggles = 1,
	}
}
