//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(603, "Class 3 Supply Category - Petroleum, Oils, Lubricants", 8)]
	public enum Class3SupplyCategoryPetroleumOilsLubricants : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("a5b30b1d-5bf1-493a-8756-729f96740d84", Description="Other")]
		Other = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("7d6e9ff4-cfca-4cb5-a60b-4670b9cf1b94", Description="A - POL for Air Vehicles")]
		APOLForAirVehicles = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("b0749291-abf7-4643-94ed-d2f5335398b8", Description="W - POL for Land Vehicles")]
		WPOLForLandVehicles = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("531a5c1a-9e2a-4e72-bdc4-22e9581b6c7a", Description="P - Packaged POL")]
		PPackagedPOL = 4,
	}
}
