//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(609, "Class 9 Supply Category - Repair Parts and Components", 8)]
	public enum Class9SupplyCategoryRepairPartsAndComponents : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("4d1da716-ba7d-4348-925d-adea33a68acd", Description="Other")]
		Other = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("4e242ef1-df5b-4299-9861-81b829fc6af3", Description="A - Air")]
		AAir = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d2110652-536f-480e-a3d9-8145a6e52ca6", Description="B - Ground Support Materiel")]
		BGroundSupportMateriel = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("83a6013e-564e-43f0-aa7a-2c296abb0d8a", Description="D - Admin Vehicles")]
		DAdminVehicles = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("503d589c-98fa-4823-9706-b5648a6436fe", Description="G - Electronics")]
		GElectronics = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("8c9a2062-b1af-4aef-be76-1e98567fc3bf", Description="K - Tactical Vehicles")]
		KTacticalVehicles = 6,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("30edbf77-e86b-4b8f-aacf-788fa528cc47", Description="L - Missiles")]
		LMissiles = 7,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("fa8b867d-ae85-4211-b06f-335c4ad4ceab", Description="M - Weapons")]
		MWeapons = 8,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0040683f-c5d8-42f6-b604-1e87fc7c365c", Description="N - Special Weapons")]
		NSpecialWeapons = 9,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0547e102-7978-4cd1-a529-c1be32acd419", Description="X - Aircraft Engines")]
		XAircraftEngines = 10,
	}
}
