//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(602, "Class 2 Supply Category - Clothing, Individual Equipment, Tools, Admin. Supplies", 8)]
	public enum Class2SupplyCategoryClothingIndividualEquipmentToolsAdminSupplies : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("6c5ce3b5-663d-4829-8324-4bdfb07ae98f", Description="Other")]
		Other = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0b31daf5-f964-4f9a-8295-fba2352bf2d3", Description="A - Air")]
		AAir = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("27bf3a4d-ea7c-4e88-bb44-a2ebacc32a6d", Description="B - Ground Support Materiel")]
		BGroundSupportMateriel = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("2a856865-581e-4477-b760-e955958f1ef2", Description="E - General Supplies")]
		EGeneralSupplies = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("8b02b00d-74d9-4ef6-8457-9306f3231b80", Description="F - Clothing")]
		FClothing = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("09ce0225-1ef6-4448-9f6d-6297f92a46c6", Description="G - Electronics")]
		GElectronics = 6,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("fce5a88e-f820-47e5-bc84-a4bb21ac3816", Description="M - Weapons (Humans)")]
		MWeaponsHumans = 7,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0f45e8c2-89e6-4b01-b9a6-7cd2735b2f12", Description="T - Industrial Supplies")]
		TIndustrialSupplies = 8,
	}
}
