//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(607, "Class 7 Supply Category - Major Items", 8)]
	public enum Class7SupplyCategoryMajorItems : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("7b1793d1-f05d-490c-9b58-b86ac93cd66e", Description="Other")]
		Other = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("8f663162-d126-4465-b473-97dc35f9a973", Description="A - Air (Not used, as described in Air Domain)")]
		AAirNotUsedAsDescribedInAirDomain = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("df7fc789-8770-47dd-be08-cadbf9ff52eb", Description="B - Ground Support Materiel")]
		BGroundSupportMateriel = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("cd2b3dce-58e8-491e-a54a-11761da5b0c2", Description="D - Admin Vehicles (Not used, as described in Land Domain)")]
		DAdminVehiclesNotUsedAsDescribedInLandDomain = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9b414720-8953-4087-9219-90926129e1c0", Description="G - Electronics")]
		GElectronics = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d73d9a5b-9cca-4b52-8649-9ef85d9f0189", Description="J - Racks, Adaptors, Pylons")]
		JRacksAdaptorsPylons = 6,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("703509e1-5bb7-402e-8830-cb7c17f1fc8e", Description="K - Tactical Vehicles (Not used, as described in Land Domain)")]
		KTacticalVehiclesNotUsedAsDescribedInLandDomain = 7,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e7c6df20-eef0-4c06-b0ce-e82a09da2418", Description="L - Missiles (Not used, as described in Munition Domain)")]
		LMissilesNotUsedAsDescribedInMunitionDomain = 8,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("5e16364e-9ddb-4fcf-9075-88046aaaa232", Description="M - Weapons")]
		MWeapons = 9,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1a85f73b-364d-4ec1-8654-d6d57f1a5475", Description="N - Special Weapons")]
		NSpecialWeapons = 10,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1aa115d9-3446-48c3-a3df-038fe331d4e3", Description="X - Aircraft Engines")]
		XAircraftEngines = 11,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("3332622f-3d95-498a-93c8-21b64722ddf2", Description="Drop Tank")]
		DropTank = 20,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ee269027-a505-4292-bc9f-dc46f36d8800", Description="Conformal Fuel Tank")]
		ConformalFuelTank = 21,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("bbb5b4e6-4a6f-42d4-bc98-f6fc4640db22", Description="Luggage Pod")]
		LuggagePod = 22,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("46fa27ac-9e13-4372-8b13-4193637f5d9d", Description="ECM Pod")]
		ECMPod = 23,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("4f45122e-f6ef-4af2-9889-0905150710ad", Description="Para-Drogue")]
		ParaDrogue = 24,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9ed832a7-bc15-463f-86f8-95cbbbef4170", Description="Targeting Pod")]
		TargetingPod = 25,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0d9b746b-ba34-4bbf-ac88-305586c6bde5", Description="Fairing")]
		Fairing = 26,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e7ab8013-471d-4b21-b8fc-df5907684b36", Description="Air Refuelling Pod")]
		AirRefuellingPod = 27,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1a9f41f2-9f4e-40b5-b548-50abd8ae801d", Description="Heavy Airdrop")]
		HeavyAirdrop = 28,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("23380068-1213-48ec-943c-2e43b813b45a", Description="Container Delivery System (CDS) Airdrop")]
		ContainerDeliverySystemCDSAirdrop = 29,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("a52007e3-3254-4d25-bd70-1142ae01fce6", Description="Rocket Pod/Launcher")]
		RocketPodOrLauncher = 30,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1eb2e12f-07e3-4ff9-9a48-fb402e583729", Description="Tactical Pod")]
		TacticalPod = 31,
	}
}
