//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(375, "Component Visual Damage Status-Smoke", 2)]
	public enum ComponentVisualDamageStatusSmoke : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9c12d857-8866-4c79-b671-d81b863ad151", Description="No Smoke")]
		NoSmoke = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1276cc2c-5104-4b75-bac5-c88e815af606", Description="Light Smoke")]
		LightSmoke = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1d40e27b-00ed-4268-a706-9d098b622139", Description="Moderate Smoke")]
		ModerateSmoke = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("6f2adfc1-d6cc-43e8-8d84-de000e4fe6da", Description="Heavy Smoke")]
		HeavySmoke = 3,
	}
}
