//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(29, "Country", 16)]
	public enum Country : ushort {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4437fea-5269-11df-91f4-080069138b88", Description="Other")]
		Other = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4448930-5269-11df-8e0a-080069138b88", Description="Afghanistan (AFG)")]
		AfghanistanAFG = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c44598ca-5269-11df-b8ba-080069138b88", Description="Albania (ALB)")]
		AlbaniaALB = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c446ab48-5269-11df-aec1-080069138b88", Description="Algeria (DZA)")]
		AlgeriaDZA = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c447b510-5269-11df-9d43-080069138b88", Description="American Samoa (ASM)")]
		AmericanSamoaASM = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c448c626-5269-11df-8891-080069138b88", Description="Andorra (AND)")]
		AndorraAND = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c449d6c4-5269-11df-beea-080069138b88", Description="Angola (AGO)")]
		AngolaAGO = 6,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c44adef2-5269-11df-86b9-080069138b88", Description="Anguilla (AIA)")]
		AnguillaAIA = 7,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c44bee64-5269-11df-b85e-080069138b88", Description="Antarctica (ATA)")]
		AntarcticaATA = 8,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c44cfdcc-5269-11df-a8c9-080069138b88", Description="Antigua and Barbuda (ATG)")]
		AntiguaAndBarbudaATG = 9,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c44e0a64-5269-11df-8c47-080069138b88", Description="Argentina (ARG)")]
		ArgentinaARG = 10,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c44f17b0-5269-11df-8be4-080069138b88", Description="Aruba (ABW)")]
		ArubaABW = 11,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c450317c-5269-11df-8f0d-080069138b88", Description="Ashmore and Cartier Islands (Australia)")]
		[System.ObsoleteAttribute("Use Australia")]
		AshmoreAndCartierIslandsAustralia = 12,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c451409e-5269-11df-b37f-080069138b88", Description="Australia (AUS)")]
		AustraliaAUS = 13,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4524e9e-5269-11df-a488-080069138b88", Description="Austria (AUT)")]
		AustriaAUT = 14,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4535b22-5269-11df-bc10-080069138b88", Description="Bahamas (BHS)")]
		BahamasBHS = 15,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4546562-5269-11df-8eac-080069138b88", Description="Bahrain (BHR)")]
		BahrainBHR = 16,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c45578f8-5269-11df-9539-080069138b88", Description="Baker Island (United States)")]
		[System.ObsoleteAttribute("Use United States Minor Outlying Islands")]
		BakerIslandUnitedStates = 17,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4568838-5269-11df-a65d-080069138b88", Description="Bangladesh (BGD)")]
		BangladeshBGD = 18,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c457914c-5269-11df-a4ea-080069138b88", Description="Barbados (BRB)")]
		BarbadosBRB = 19,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c458a46a-5269-11df-85ad-080069138b88", Description="Bassas da India (France)")]
		[System.ObsoleteAttribute("Use French Southern Territories")]
		BassasDaIndiaFrance = 20,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c459b3dc-5269-11df-8442-080069138b88", Description="Belgium (BEL)")]
		BelgiumBEL = 21,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c45abb6a-5269-11df-b896-080069138b88", Description="Belize (BLZ)")]
		BelizeBLZ = 22,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("894B64AE-C16A-42a2-8187-EFB11132E146", Description="Benin (BEN)")]
		BeninBEN = 23,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c45de5e2-5269-11df-a9ea-080069138b88", Description="Bermuda (BMU)")]
		BermudaBMU = 24,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c45ef3f6-5269-11df-9f84-080069138b88", Description="Bhutan (BTN)")]
		BhutanBTN = 25,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c46003f4-5269-11df-ab86-080069138b88", Description="Bolivia (Plurinational State of) (BOL)")]
		BoliviaPlurinationalStateOfBOL = 26,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4611014-5269-11df-962e-080069138b88", Description="Botswana (BWA)")]
		BotswanaBWA = 27,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4621ebe-5269-11df-afd8-080069138b88", Description="Bouvet Island (BVT)")]
		BouvetIslandBVT = 28,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4632c82-5269-11df-abad-080069138b88", Description="Brazil (BRA)")]
		BrazilBRA = 29,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c46436c2-5269-11df-a101-080069138b88", Description="British Indian Ocean Territory (IOT)")]
		BritishIndianOceanTerritoryIOT = 30,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4654cec-5269-11df-a478-080069138b88", Description="Virgin Islands (British) (VGB)")]
		VirginIslandsBritishVGB = 31,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4666410-5269-11df-8c10-080069138b88", Description="Brunei Darussalam (BRN)")]
		BruneiDarussalamBRN = 32,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4676dd8-5269-11df-b09f-080069138b88", Description="Bulgaria (BGR)")]
		BulgariaBGR = 33,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("F737EB90-E2C3-48ae-98B8-4A6AC9603C68", Description="Burkina Faso (BFA)")]
		BurkinaFasoBFA = 34,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("E5756B0E-4771-417d-AD3F-92872B119C51", Description="Myanmar (MMR)")]
		MyanmarMMR = 35,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c46ccba2-5269-11df-88a8-080069138b88", Description="Burundi (BDI)")]
		BurundiBDI = 36,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c46ddcc2-5269-11df-a5ed-080069138b88", Description="Cambodia (KHM)")]
		CambodiaKHM = 37,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c46eed38-5269-11df-8a39-080069138b88", Description="Cameroon (CMR)")]
		CameroonCMR = 38,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c46ffdd6-5269-11df-9067-080069138b88", Description="Canada (CAN)")]
		CanadaCAN = 39,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4710a6e-5269-11df-a595-080069138b88", Description="Cabo Verde (CPV)")]
		CaboVerdeCPV = 40,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4721a12-5269-11df-b950-080069138b88", Description="Cayman Islands (CYM)")]
		CaymanIslandsCYM = 41,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c47329ca-5269-11df-90c2-080069138b88", Description="Central African Republic (CAF)")]
		CentralAfricanRepublicCAF = 42,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c47436b2-5269-11df-b9fa-080069138b88", Description="Chad (TCD)")]
		ChadTCD = 43,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c475471e-5269-11df-9327-080069138b88", Description="Chile (CHL)")]
		ChileCHL = 44,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c476565e-5269-11df-97f6-080069138b88", Description="China, People\'s Republic of (CHN)")]
		ChinaPeoplesRepublicOfCHN = 45,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4776008-5269-11df-9122-080069138b88", Description="Christmas Island (CXR)")]
		ChristmasIslandCXR = 46,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4787074-5269-11df-a642-080069138b88", Description="Cocos (Keeling) Islands (CCK)")]
		CocosKeelingIslandsCCK = 47,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c47984c8-5269-11df-ad81-080069138b88", Description="Colombia (COL)")]
		ColombiaCOL = 48,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c47a8e18-5269-11df-9441-080069138b88", Description="Comoros (COM)")]
		ComorosCOM = 49,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c47b9b32-5269-11df-8bb1-080069138b88", Description="Congo (COG)")]
		CongoCOG = 50,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c47cabf8-5269-11df-9fc5-080069138b88", Description="Cook Islands (COK)")]
		CookIslandsCOK = 51,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c47db872-5269-11df-ba77-080069138b88", Description="Coral Sea Islands (Australia)")]
		[System.ObsoleteAttribute("Use Australia")]
		CoralSeaIslandsAustralia = 52,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c47ec67c-5269-11df-8bf1-080069138b88", Description="Costa Rica (CRI)")]
		CostaRicaCRI = 53,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c47fd72e-5269-11df-8eec-080069138b88", Description="Cuba (CUB)")]
		CubaCUB = 54,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c480e114-5269-11df-a98c-080069138b88", Description="Cyprus (CYP)")]
		CyprusCYP = 55,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c481f82e-5269-11df-b986-080069138b88", Description="Czechoslovakia (CSK)")]
		[System.ObsoleteAttribute("Now dissolved; succeeded by the Czech Republic and Slovakia")]
		CzechoslovakiaCSK = 56,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4830cc8-5269-11df-8dd6-080069138b88", Description="Denmark (DNK)")]
		DenmarkDNK = 57,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c484171c-5269-11df-8db2-080069138b88", Description="Djibouti (DJI)")]
		DjiboutiDJI = 58,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4852940-5269-11df-ac47-080069138b88", Description="Dominica (DMA)")]
		DominicaDMA = 59,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4863830-5269-11df-a470-080069138b88", Description="Dominican Republic (DOM)")]
		DominicanRepublicDOM = 60,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4874054-5269-11df-9031-080069138b88", Description="Ecuador (ECU)")]
		EcuadorECU = 61,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4884eb8-5269-11df-b7ed-080069138b88", Description="Egypt (EGY)")]
		EgyptEGY = 62,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c489606e-5269-11df-8eba-080069138b88", Description="El Salvador (SLV)")]
		ElSalvadorSLV = 63,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c48a691e-5269-11df-84a3-080069138b88", Description="Equatorial Guinea (GNQ)")]
		EquatorialGuineaGNQ = 64,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c48b76b0-5269-11df-9031-080069138b88", Description="Ethiopia (ETH)")]
		EthiopiaETH = 65,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c48c9022-5269-11df-9a2f-080069138b88", Description="Europa Island (France)")]
		[System.ObsoleteAttribute("Use French Southern Territories")]
		EuropaIslandFrance = 66,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c48da110-5269-11df-ab72-080069138b88", Description="Falkland Islands (Malvinas) (FLK)")]
		FalklandIslandsMalvinasFLK = 67,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c48eb2ee-5269-11df-8c62-080069138b88", Description="Faroe Islands (FRO)")]
		FaroeIslandsFRO = 68,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c48fc10c-5269-11df-a58b-080069138b88", Description="Fiji (FJI)")]
		FijiFJI = 69,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c490ea64-5269-11df-b752-080069138b88", Description="Finland (FIN)")]
		FinlandFIN = 70,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4920412-5269-11df-bca5-080069138b88", Description="France (FRA)")]
		FranceFRA = 71,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c493130c-5269-11df-9f8e-080069138b88", Description="French Guiana (GUF)")]
		FrenchGuianaGUF = 72,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c49424fe-5269-11df-8dd2-080069138b88", Description="French Polynesia (PYF)")]
		FrenchPolynesiaPYF = 73,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c49534a2-5269-11df-93c1-080069138b88", Description="French Southern Territories (ATF)")]
		FrenchSouthernTerritoriesATF = 74,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c49645e0-5269-11df-9aae-080069138b88", Description="Gabon (GAB)")]
		GabonGAB = 75,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4975480-5269-11df-b18d-080069138b88", Description="Gambia, The (GMB)")]
		GambiaTheGMB = 76,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4985c36-5269-11df-a7af-080069138b88", Description="Gaza Strip (Israel)")]
		[System.ObsoleteAttribute("Use Israel instead")]
		GazaStripIsrael = 77,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4996f68-5269-11df-a144-080069138b88", Description="Germany (DEU)")]
		GermanyDEU = 78,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c49a7e4e-5269-11df-aad1-080069138b88", Description="Ghana (GHA)")]
		GhanaGHA = 79,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c49b8708-5269-11df-9417-080069138b88", Description="Gibraltar (GIB)")]
		GibraltarGIB = 80,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c49c99ea-5269-11df-bb6f-080069138b88", Description="Glorioso Islands (France)")]
		[System.ObsoleteAttribute("Use French Southern Territories")]
		GloriosoIslandsFrance = 81,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c49da8bc-5269-11df-b487-080069138b88", Description="Greece (GRC)")]
		GreeceGRC = 82,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c49eb126-5269-11df-8eaa-080069138b88", Description="Greenland (GRL)")]
		GreenlandGRL = 83,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c49fbf26-5269-11df-a2d0-080069138b88", Description="Grenada (GRD)")]
		GrenadaGRD = 84,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4a0d172-5269-11df-aa83-080069138b88", Description="Guadeloupe (GLP)")]
		GuadeloupeGLP = 85,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4a1db80-5269-11df-a761-080069138b88", Description="Guam (GUM)")]
		GuamGUM = 86,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4a2ec14-5269-11df-9611-080069138b88", Description="Guatemala (GTM)")]
		GuatemalaGTM = 87,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4a3fdf2-5269-11df-913b-080069138b88", Description="Guernsey (GGY)")]
		GuernseyGGY = 88,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4a50774-5269-11df-b2b3-080069138b88", Description="Guinea (GIN)")]
		GuineaGIN = 89,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4a6163c-5269-11df-a1b5-080069138b88", Description="Guinea-Bissau (GNB)")]
		GuineaBissauGNB = 90,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4a72874-5269-11df-9358-080069138b88", Description="Guyana (GUY)")]
		GuyanaGUY = 91,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4a82fee-5269-11df-9e8a-080069138b88", Description="Haiti (HTI)")]
		HaitiHTI = 92,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4a93ff6-5269-11df-bf62-080069138b88", Description="Heard Island and McDonald Islands (HMD)")]
		HeardIslandAndMcdonaldIslandsHMD = 93,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4aa544a-5269-11df-960f-080069138b88", Description="Honduras (HND)")]
		HondurasHND = 94,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4ab6628-5269-11df-8c3d-080069138b88", Description="Hong Kong (HKG)")]
		HongKongHKG = 95,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4ac76ee-5269-11df-b28a-080069138b88", Description="Howland Island (United States)")]
		[System.ObsoleteAttribute("Use United States Minor Outlying Islands")]
		HowlandIslandUnitedStates = 96,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4ad8872-5269-11df-9016-080069138b88", Description="Hungary (HUN)")]
		HungaryHUN = 97,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4ae956e-5269-11df-9568-080069138b88", Description="Iceland (ISL)")]
		IcelandISL = 98,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4afa2f6-5269-11df-b9c5-080069138b88", Description="India (IND)")]
		IndiaIND = 99,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4b0b06a-5269-11df-b8bf-080069138b88", Description="Indonesia (IDN)")]
		IndonesiaIDN = 100,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4b1bdc0-5269-11df-8128-080069138b88", Description="Iran (Islamic Republic of) (IRN)")]
		IranIslamicRepublicOfIRN = 101,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4b2ce5e-5269-11df-aa5d-080069138b88", Description="Iraq (IRQ)")]
		IraqIRQ = 102,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4b3db5a-5269-11df-8cde-080069138b88", Description="Ireland (IRL)")]
		IrelandIRL = 104,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4b4e4c8-5269-11df-aca7-080069138b88", Description="Israel (ISR)")]
		IsraelISR = 105,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4b5f674-5269-11df-b832-080069138b88", Description="Italy (ITA)")]
		ItalyITA = 106,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4b70438-5269-11df-8e3f-080069138b88", Description="Cote d\'Ivoire (CIV)")]
		CoteDivoireCIV = 107,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4b9229a-5269-11df-8e61-080069138b88", Description="Jamaica (JAM)")]
		JamaicaJAM = 108,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4ba30f4-5269-11df-80b4-080069138b88", Description="Jan Mayen (Norway)")]
		[System.ObsoleteAttribute("Use Svalbard and Jan Mayen")]
		JanMayenNorway = 109,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4bb38dc-5269-11df-9605-080069138b88", Description="Japan (JPN)")]
		JapanJPN = 110,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4bc47f4-5269-11df-ac53-080069138b88", Description="Jarvis Island (United States)")]
		[System.ObsoleteAttribute("Use United States Minor Outlying Islands")]
		JarvisIslandUnitedStates = 111,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4bd5bc6-5269-11df-8a78-080069138b88", Description="Jersey (JEY)")]
		JerseyJEY = 112,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4be6502-5269-11df-88de-080069138b88", Description="Johnston Atoll (United States)")]
		[System.ObsoleteAttribute("Island no longer occupied, removed from ISO 3166 country list")]
		JohnstonAtollUnitedStates = 113,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4bf7488-5269-11df-a64b-080069138b88", Description="Jordan (JOR)")]
		JordanJOR = 114,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4c08526-5269-11df-b10b-080069138b88", Description="Juan de Nova Island")]
		[System.ObsoleteAttribute("Use French Southern Territories")]
		JuanDeNovaIsland = 115,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4c19312-5269-11df-bda7-080069138b88", Description="Kenya (KEN)")]
		KenyaKEN = 116,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4c2a356-5269-11df-a6c0-080069138b88", Description="Kingman Reef (United States)")]
		[System.ObsoleteAttribute("Use United States Minor Outlying Islands")]
		KingmanReefUnitedStates = 117,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4c3b264-5269-11df-962a-080069138b88", Description="Kiribati (KIR)")]
		KiribatiKIR = 118,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4c4bc18-5269-11df-b5c8-080069138b88", Description="Korea (Democratic People\'s Republic of) (PRK)")]
		KoreaDemocraticPeoplesRepublicOfPRK = 119,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4c5d094-5269-11df-867b-080069138b88", Description="Korea (Republic of) (KOR)")]
		KoreaRepublicOfKOR = 120,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4c6e074-5269-11df-be93-080069138b88", Description="Kuwait (KWT)")]
		KuwaitKWT = 121,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4c7e78a-5269-11df-8602-080069138b88", Description="Lao People\'s Democratic Republic (LAO)")]
		LaoPeoplesDemocraticRepublicLAO = 122,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4c8f954-5269-11df-86b3-080069138b88", Description="Lebanon (LBN)")]
		LebanonLBN = 123,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4ca103c-5269-11df-b867-080069138b88", Description="Lesotho (LSO)")]
		LesothoLSO = 124,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4cb1af4-5269-11df-b39f-080069138b88", Description="Liberia (LBR)")]
		LiberiaLBR = 125,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4cc2fde-5269-11df-baca-080069138b88", Description="Libya (LBY)")]
		LibyaLBY = 126,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4cd4342-5269-11df-8769-080069138b88", Description="Liechtenstein (LIE)")]
		LiechtensteinLIE = 127,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4ce4c6a-5269-11df-b653-080069138b88", Description="Luxembourg (LUX)")]
		LuxembourgLUX = 128,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4cf5a1a-5269-11df-839d-080069138b88", Description="Madagascar (MDG)")]
		MadagascarMDG = 129,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4d06a86-5269-11df-8860-080069138b88", Description="Macao (MAC)")]
		MacaoMAC = 130,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4d1773c-5269-11df-b1bf-080069138b88", Description="Malawi (MWI)")]
		MalawiMWI = 131,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4d286e0-5269-11df-b23b-080069138b88", Description="Malaysia (MYS)")]
		MalaysiaMYS = 132,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4d394fe-5269-11df-80a5-080069138b88", Description="Maldives (MDV)")]
		MaldivesMDV = 133,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4d49d9a-5269-11df-9921-080069138b88", Description="Mali (MLI)")]
		MaliMLI = 134,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4d5af64-5269-11df-9439-080069138b88", Description="Malta (MLT)")]
		MaltaMLT = 135,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4d6bdb4-5269-11df-80e5-080069138b88", Description="Isle of Man (IMN)")]
		IsleOfManIMN = 136,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4d7c7a4-5269-11df-8822-080069138b88", Description="Marshall Islands (MHL)")]
		MarshallIslandsMHL = 137,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4d8db08-5269-11df-a72e-080069138b88", Description="Martinique (MTQ)")]
		MartiniqueMTQ = 138,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4d9eaf2-5269-11df-a897-080069138b88", Description="Mauritania (MRT)")]
		MauritaniaMRT = 139,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4daf42e-5269-11df-8ea8-080069138b88", Description="Mauritius (MUS)")]
		MauritiusMUS = 140,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4dc030a-5269-11df-bff8-080069138b88", Description="Mayotte (MYT)")]
		MayotteMYT = 141,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4dd1538-5269-11df-b49b-080069138b88", Description="Mexico (MEX)")]
		MexicoMEX = 142,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4de1ea6-5269-11df-8e1b-080069138b88", Description="Micronesia (Federated States of) (FSM)")]
		MicronesiaFederatedStatesOfFSM = 143,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4df2dd2-5269-11df-89bc-080069138b88", Description="Monaco (MCO)")]
		MonacoMCO = 144,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4e040be-5269-11df-911c-080069138b88", Description="Mongolia (MNG)")]
		MongoliaMNG = 145,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4e1504e-5269-11df-9ded-080069138b88", Description="Montserrat (MSR)")]
		MontserratMSR = 146,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4e26286-5269-11df-8453-080069138b88", Description="Morocco (MAR)")]
		MoroccoMAR = 147,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4e36f96-5269-11df-b84c-080069138b88", Description="Mozambique (MOZ)")]
		MozambiqueMOZ = 148,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4e479cc-5269-11df-ae79-080069138b88", Description="Namibia (NAM)")]
		NamibiaNAM = 149,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4e58d26-5269-11df-b4ec-080069138b88", Description="Nauru (NRU)")]
		NauruNRU = 150,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4e69b94-5269-11df-b3cc-080069138b88", Description="Navassa Island (United States)")]
		[System.ObsoleteAttribute("Use United States Minor Outlying Islands")]
		NavassaIslandUnitedStates = 151,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4e7a534-5269-11df-81b3-080069138b88", Description="Nepal (NPL)")]
		NepalNPL = 152,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4e8be56-5269-11df-af13-080069138b88", Description="Netherlands (NLD)")]
		NetherlandsNLD = 153,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4e9d4d0-5269-11df-b84d-080069138b88", Description="Netherlands Antilles (Curacao, Bonaire, Saba, Sint Maarten Sint Eustatius)")]
		[System.ObsoleteAttribute("Use Netherlands")]
		NetherlandsAntillesCuracaoBonaireSabaSintMaartenSintEustatius = 154,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4eae37a-5269-11df-9d07-080069138b88", Description="New Caledonia (NCL)")]
		NewCaledoniaNCL = 155,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4ebf1f2-5269-11df-8f58-080069138b88", Description="New Zealand (NZL)")]
		NewZealandNZL = 156,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4ed28ba-5269-11df-a331-080069138b88", Description="Nicaragua (NIC)")]
		NicaraguaNIC = 157,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4ee3930-5269-11df-8e02-080069138b88", Description="Niger (NER)")]
		NigerNER = 158,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4ef4820-5269-11df-8ad1-080069138b88", Description="Nigeria (NGA)")]
		NigeriaNGA = 159,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4f0583c-5269-11df-82ba-080069138b88", Description="Niue (NIU)")]
		NiueNIU = 160,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4f16650-5269-11df-abe1-080069138b88", Description="Norfolk Island (NFK)")]
		NorfolkIslandNFK = 161,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4f277de-5269-11df-ab83-080069138b88", Description="Northern Mariana Islands (MNP)")]
		NorthernMarianaIslandsMNP = 162,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4f38854-5269-11df-9721-080069138b88", Description="Norway (NOR)")]
		NorwayNOR = 163,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4f490b4-5269-11df-b8ab-080069138b88", Description="Oman (OMN)")]
		OmanOMN = 164,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4f5a30a-5269-11df-b150-080069138b88", Description="Pakistan (PAK)")]
		PakistanPAK = 165,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4f6b222-5269-11df-a8af-080069138b88", Description="Palmyra Atoll (United States)")]
		[System.ObsoleteAttribute("Use United States Minor Outlying Islands")]
		PalmyraAtollUnitedStates = 166,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4f7be10-5269-11df-9e2b-080069138b88", Description="Panama (PAN)")]
		PanamaPAN = 168,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4f8cf58-5269-11df-9fba-080069138b88", Description="Papua New Guinea (PNG)")]
		PapuaNewGuineaPNG = 169,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4f9e096-5269-11df-88ee-080069138b88", Description="Paracel Islands (International - Occupied by China, also claimed by Taiwan and Vi" +
			"etnam)")]
		[System.ObsoleteAttribute()]
		ParacelIslandsInternationalOccupiedByChinaAlsoClaimedByTaiwanAndVietnam = 170,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4faeebe-5269-11df-a845-080069138b88", Description="Paraguay (PRY)")]
		ParaguayPRY = 171,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4fc0470-5269-11df-b86a-080069138b88", Description="Peru (PER)")]
		PeruPER = 172,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4fd120c-5269-11df-a59f-080069138b88", Description="Philippines (PHL)")]
		PhilippinesPHL = 173,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4fe1d14-5269-11df-9ff0-080069138b88", Description="Pitcairn (PCN)")]
		PitcairnPCN = 174,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4ff30c8-5269-11df-8d2b-080069138b88", Description="Poland (POL)")]
		PolandPOL = 175,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5003f04-5269-11df-abfe-080069138b88", Description="Portugal (PRT)")]
		PortugalPRT = 176,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c50148f4-5269-11df-b029-080069138b88", Description="Puerto Rico (PRI)")]
		PuertoRicoPRI = 177,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5025956-5269-11df-9f90-080069138b88", Description="Qatar (QAT)")]
		QatarQAT = 178,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5036c56-5269-11df-a8f6-080069138b88", Description="Reunion (REU)")]
		ReunionREU = 179,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5047466-5269-11df-bf45-080069138b88", Description="Romania (ROU)")]
		RomaniaROU = 180,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5058360-5269-11df-87d8-080069138b88", Description="Rwanda (RWA)")]
		RwandaRWA = 181,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5069458-5269-11df-b881-080069138b88", Description="Saint Kitts and Nevis (KNA)")]
		SaintKittsAndNevisKNA = 182,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c507aa82-5269-11df-bcdd-080069138b88", Description="Saint Helena, Ascension and Tristan da Cunha (SHN)")]
		SaintHelenaAscensionAndTristanDaCunhaSHN = 183,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c508bb16-5269-11df-a7bc-080069138b88", Description="Saint Lucia (LCA)")]
		SaintLuciaLCA = 184,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c509cc7c-5269-11df-af8a-080069138b88", Description="Saint Pierre and Miquelon (SPM)")]
		SaintPierreAndMiquelonSPM = 185,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c50ad946-5269-11df-b0e1-080069138b88", Description="Saint Vincent and the Grenadines (VCT)")]
		SaintVincentAndTheGrenadinesVCT = 186,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c50beab6-5269-11df-9d1b-080069138b88", Description="San Marino (SMR)")]
		SanMarinoSMR = 187,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c50cf834-5269-11df-b031-080069138b88", Description="Sao Tome and Principe (STP)")]
		SaoTomeAndPrincipeSTP = 188,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c50e0580-5269-11df-81b6-080069138b88", Description="Saudi Arabia (SAU)")]
		SaudiArabiaSAU = 189,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c50f142a-5269-11df-a926-080069138b88", Description="Senegal (SEN)")]
		SenegalSEN = 190,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c51024b4-5269-11df-8486-080069138b88", Description="Seychelles (SYC)")]
		SeychellesSYC = 191,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5113084-5269-11df-9876-080069138b88", Description="Sierra Leone (SLE)")]
		SierraLeoneSLE = 192,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5123eca-5269-11df-b75d-080069138b88", Description="Singapore (SGP)")]
		SingaporeSGP = 193,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5134ed2-5269-11df-b821-080069138b88", Description="Solomon Islands (SLB)")]
		SolomonIslandsSLB = 194,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5145994-5269-11df-ba5c-080069138b88", Description="Somalia (SOM)")]
		SomaliaSOM = 195,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c51568ca-5269-11df-9e97-080069138b88", Description="South Georgia and the South Sandwich Islands (SGS)")]
		SouthGeorgiaAndTheSouthSandwichIslandsSGS = 196,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5167f12-5269-11df-87bb-080069138b88", Description="South Africa (ZAF)")]
		SouthAfricaZAF = 197,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5178858-5269-11df-95cc-080069138b88", Description="Spain (ESP)")]
		SpainESP = 198,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5189860-5269-11df-a746-080069138b88", Description="Spratly Islands (International - parts occupied and claimed by China,Malaysia, Ph" +
			"ilippines, Taiwan, Vietnam)")]
		[System.ObsoleteAttribute()]
		SpratlyIslandsInternationalPartsOccupiedAndClaimedByChinaMalaysiaPhilippinesTaiwanVietnam = 199,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c519afe8-5269-11df-a5bb-080069138b88", Description="Sri Lanka (LKA)")]
		SriLankaLKA = 200,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c51ac31a-5269-11df-adad-080069138b88", Description="Sudan (SDN)")]
		SudanSDN = 201,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c51bd2dc-5269-11df-86ed-080069138b88", Description="Suriname (SUR)")]
		SurinameSUR = 202,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c51ce0fa-5269-11df-8461-080069138b88", Description="Svalbard (Norway)")]
		[System.ObsoleteAttribute("Use Svalbard and Jan Mayen")]
		SvalbardNorway = 203,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c51deed2-5269-11df-b718-080069138b88", Description="Eswatini (SWZ)")]
		EswatiniSWZ = 204,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c51efd68-5269-11df-989e-080069138b88", Description="Sweden (SWE)")]
		SwedenSWE = 205,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5200d16-5269-11df-9547-080069138b88", Description="Switzerland (CHE)")]
		SwitzerlandCHE = 206,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c52116c0-5269-11df-9c17-080069138b88", Description="Syrian Arab Republic (SYR)")]
		SyrianArabRepublicSYR = 207,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c522284e-5269-11df-833b-080069138b88", Description="Taiwan, Province of China (TWN)")]
		TaiwanProvinceOfChinaTWN = 208,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5233680-5269-11df-9d4c-080069138b88", Description="Tanzania, United Republic of (TZA)")]
		TanzaniaUnitedRepublicOfTZA = 209,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5244124-5269-11df-9da7-080069138b88", Description="Thailand (THA)")]
		ThailandTHA = 210,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5255230-5269-11df-88d8-080069138b88", Description="Togo (TGO)")]
		TogoTGO = 211,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5266c06-5269-11df-8036-080069138b88", Description="Tokelau (TKL)")]
		TokelauTKL = 212,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c52776f0-5269-11df-89c3-080069138b88", Description="Tonga (TON)")]
		TongaTON = 213,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c52886bc-5269-11df-bee6-080069138b88", Description="Trinidad and Tobago (TTO)")]
		TrinidadAndTobagoTTO = 214,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5299674-5269-11df-8ec3-080069138b88", Description="Tromelin Island (France)")]
		[System.ObsoleteAttribute("Use French Southern Territories")]
		TromelinIslandFrance = 215,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c52aa5d2-5269-11df-8361-080069138b88", Description="Palau (PLW)")]
		PalauPLW = 216,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c52bb8b4-5269-11df-9b64-080069138b88", Description="Tunisia (TUN)")]
		TunisiaTUN = 217,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c52cc7a4-5269-11df-a516-080069138b88", Description="Turkey (TUR)")]
		TurkeyTUR = 218,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c52dd40a-5269-11df-8766-080069138b88", Description="Turks and Caicos Islands (TCA)")]
		TurksAndCaicosIslandsTCA = 219,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c52ee3ae-5269-11df-9903-080069138b88", Description="Tuvalu (TUV)")]
		TuvaluTUV = 220,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c52ff2bc-5269-11df-844d-080069138b88", Description="Uganda (UGA)")]
		UgandaUGA = 221,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c530fb44-5269-11df-9ca6-080069138b88", Description="Russia (RUS)")]
		RussiaRUS = 222,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5320f66-5269-11df-8813-080069138b88", Description="United Arab Emirates (ARE)")]
		UnitedArabEmiratesARE = 223,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5331f0a-5269-11df-9606-080069138b88", Description="United Kingdom of Great Britain and Northern Ireland (GBR)")]
		UnitedKingdomOfGreatBritainAndNorthernIrelandGBR = 224,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5342896-5269-11df-982f-080069138b88", Description="United States of America (USA)")]
		UnitedStatesOfAmericaUSA = 225,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c53539c0-5269-11df-a05a-080069138b88", Description="Uruguay (URY)")]
		UruguayURY = 226,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c53647f2-5269-11df-a6e2-080069138b88", Description="Vanuatu (VUT)")]
		VanuatuVUT = 227,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c53750de-5269-11df-9d24-080069138b88", Description="Holy See (VAT)")]
		HolySeeVAT = 228,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5386208-5269-11df-90ad-080069138b88", Description="Venezuela (Bolivarian Republic of) (VEN)")]
		VenezuelaBolivarianRepublicOfVEN = 229,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5396f18-5269-11df-9db1-080069138b88", Description="Viet Nam (VNM)")]
		VietNamVNM = 230,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c53a7c3c-5269-11df-9dee-080069138b88", Description="Virgin Islands (U.S.) (VIR)")]
		VirginIslandsUSVIR = 231,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c53b8c76-5269-11df-ba0a-080069138b88", Description="Wake Island (United States)")]
		[System.ObsoleteAttribute("Use United States Minor Outlying Islands")]
		WakeIslandUnitedStates = 232,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c53c9c60-5269-11df-ad8d-080069138b88", Description="Wallis and Futuna (WLF)")]
		WallisAndFutunaWLF = 233,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c53da9de-5269-11df-8557-080069138b88", Description="Western Sahara (ESH)")]
		WesternSaharaESH = 234,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c53eb874-5269-11df-b34f-080069138b88", Description="West Bank (Israel)")]
		[System.ObsoleteAttribute("Use Israel instead")]
		WestBankIsrael = 235,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c53fca16-5269-11df-9e17-080069138b88", Description="Samoa (WSM)")]
		SamoaWSM = 236,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c540d212-5269-11df-97a9-080069138b88", Description="Yemen (YEM)")]
		YemenYEM = 237,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c541e472-5269-11df-a5ad-080069138b88", Description="Serbia and Montenegro")]
		[System.ObsoleteAttribute()]
		SerbiaAndMontenegro = 240,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c542f4fc-5269-11df-afcc-080069138b88", Description="Zaire")]
		[System.ObsoleteAttribute("Now Democratic Republic of the Congo")]
		Zaire = 241,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c543fe2e-5269-11df-85c5-080069138b88", Description="Zambia (ZMB)")]
		ZambiaZMB = 242,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5451840-5269-11df-849b-080069138b88", Description="Zimbabwe (ZWE)")]
		ZimbabweZWE = 243,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c546280c-5269-11df-a7b8-080069138b88", Description="Armenia (ARM)")]
		ArmeniaARM = 244,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5473364-5269-11df-9a37-080069138b88", Description="Azerbaijan (AZE)")]
		AzerbaijanAZE = 245,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c548643c-5269-11df-b59a-080069138b88", Description="Belarus (BLR)")]
		BelarusBLR = 246,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5497bd8-5269-11df-a9c7-080069138b88", Description="Bosnia and Herzegovina (BIH)")]
		BosniaAndHerzegovinaBIH = 247,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c54a86fe-5269-11df-872c-080069138b88", Description="Clipperton Island (France)")]
		[System.ObsoleteAttribute("Use French Southern Territories")]
		ClippertonIslandFrance = 248,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c54b9882-5269-11df-8dc7-080069138b88", Description="Croatia (HRV)")]
		CroatiaHRV = 249,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c54cabc8-5269-11df-8662-080069138b88", Description="Estonia (EST)")]
		EstoniaEST = 250,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c54db392-5269-11df-8ce1-080069138b88", Description="Georgia (GEO)")]
		GeorgiaGEO = 251,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c54ec23c-5269-11df-a09f-080069138b88", Description="Kazakhstan (KAZ)")]
		KazakhstanKAZ = 252,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c54fd38e-5269-11df-9855-080069138b88", Description="Kyrgyzstan (KGZ)")]
		KyrgyzstanKGZ = 253,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c550de0a-5269-11df-98c4-080069138b88", Description="Latvia (LVA)")]
		LatviaLVA = 254,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c551ebba-5269-11df-81e0-080069138b88", Description="Lithuania (LTU)")]
		LithuaniaLTU = 255,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c552fda2-5269-11df-ad78-080069138b88", Description="North Macedonia (MKD)")]
		NorthMacedoniaMKD = 256,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c554079c-5269-11df-98ef-080069138b88", Description="Midway Islands (United States)")]
		[System.ObsoleteAttribute("Use United States Minor Outlying Islands")]
		MidwayIslandsUnitedStates = 257,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5551786-5269-11df-970c-080069138b88", Description="Moldova (Republic of) (MDA)")]
		MoldovaRepublicOfMDA = 258,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c55626c6-5269-11df-a061-080069138b88", Description="Montenegro (MNE)")]
		MontenegroMNE = 259,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5573322-5269-11df-8128-080069138b88", Description="Russia")]
		[System.ObsoleteAttribute("Replaced by country code 222")]
		Russia = 260,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c558423a-5269-11df-9f2f-080069138b88", Description="Serbia and Montenegro (Montenegro to separate)")]
		[System.ObsoleteAttribute()]
		SerbiaAndMontenegroMontenegroToSeparate = 261,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c55953e6-5269-11df-bcb3-080069138b88", Description="Slovenia (SVN)")]
		SloveniaSVN = 262,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c55a5c96-5269-11df-a952-080069138b88", Description="Tajikistan (TJK)")]
		TajikistanTJK = 263,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c55b6d3e-5269-11df-b140-080069138b88", Description="Turkmenistan (TKM)")]
		TurkmenistanTKM = 264,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c55c8066-5269-11df-b26b-080069138b88", Description="Ukraine (UKR)")]
		UkraineUKR = 265,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c55d8c5e-5269-11df-870d-080069138b88", Description="Uzbekistan (UZB)")]
		UzbekistanUZB = 266,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1165cca1-9d5c-40fc-b4d6-7685b5bf3828", Description="Czech Republic (CZE)")]
		CzechRepublicCZE = 267,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("32a54992-41cb-4633-9035-93673a2c565c", Description="Slovakia (SVK)")]
		SlovakiaSVK = 268,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("487edff6-3376-4e4c-aeca-c264eb135ee7", Description="Aaland Islands (ALA)")]
		AalandIslandsALA = 269,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("568390e5-c707-408c-86e2-ca78b18346e2", Description="Bonaire, Sint Eustatius and Saba (BES)")]
		BonaireSintEustatiusAndSabaBES = 270,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("54994fe0-c272-4aa6-a365-05d4160544d3", Description="Congo (Democratic Republic of the) (COD)")]
		CongoDemocraticRepublicOfTheCOD = 271,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("5a192cfd-48f6-4670-9f21-a9eaf30c4504", Description="Curacao (CUW)")]
		CuracaoCUW = 272,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("2e4e3581-824e-45dc-be8e-ec5dc2d26836", Description="Eritrea (ERI)")]
		EritreaERI = 273,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("611785b6-2f23-441c-915b-1546e094c5ef", Description="Saint Barthelemy (BLM)")]
		SaintBarthelemyBLM = 274,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("4fd846f0-96e6-4b9c-b18a-51ce2757e2a4", Description="Saint Martin (French Part) (MAF)")]
		SaintMartinFrenchPartMAF = 275,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("885f4806-a613-49fd-9d47-3b020d1c53ca", Description="Serbia (SRB)")]
		SerbiaSRB = 276,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("91dab074-263d-4040-a4b6-f6c0b8f23a42", Description="Sint Maarten (Dutch part) (SXM)")]
		SintMaartenDutchPartSXM = 277,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1d826a8b-9bc8-41ae-8bad-487407996b92", Description="South Sudan (SSD)")]
		SouthSudanSSD = 278,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("4bbc16bb-6d61-4e3b-8bf8-eac296c6a624", Description="Svalbard and Jan Mayen (SJM)")]
		SvalbardAndJanMayenSJM = 279,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("a65f5244-e346-4808-b0fb-faa4e3518bed", Description="Timor-Leste (TLS)")]
		TimorLesteTLS = 280,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("64d78320-495e-4602-83e9-c07e6ba55de5", Description="United States Minor Outlying Islands (UMI)")]
		UnitedStatesMinorOutlyingIslandsUMI = 281,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c1efc87a-ea2b-4aa4-8f1b-405245c83a42", Description="Palestine, State of (PSE)")]
		PalestineStateOfPSE = 282,
	}
}
