//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(302, "DIS-PDU Status-LVC Indicator (LVC)", 2)]
	public enum DISPDUStatusLVCIndicatorLVC : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("15eb4e09-8342-4c5b-8c02-44929b64b34b", Description="No Statement")]
		NoStatement = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("b88c2923-7973-4388-b15d-c4f675f0792d", Description="Live")]
		Live = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("f72f80ff-22e7-455b-949a-149986996f61", Description="Virtual")]
		Virtual = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d85650e7-0a37-4fb5-812c-15fd59542f14", Description="Constructive")]
		Constructive = 3,
	}
}
