//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(300, "EE Attribute-State Indicator", 8)]
	public enum EEAttributeStateIndicator : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("f75b2b60-b249-4b97-9173-3c3eba412381", Description="Heartbeat Update")]
		HeartbeatUpdate = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("278ea746-75f2-4331-adb9-4855dc363bf9", Description="Changed Data")]
		ChangedData = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c8a443f5-143b-41e0-a9c1-2ab6879740b2", Description="Has Ceased")]
		HasCeased = 2,
	}
}
