//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(7, "Entity Kind", 8)]
	public enum EntityKind : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c271ae80-5269-11df-9504-080069138b88", Description="Other")]
		Other = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c272bf64-5269-11df-91f7-080069138b88", Description="Platform")]
		Platform = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c273cfc6-5269-11df-9c49-080069138b88", Description="Munition")]
		Munition = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c274dca4-5269-11df-99d3-080069138b88", Description="Life form")]
		LifeForm = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c275e766-5269-11df-a2fb-080069138b88", Description="Environmental")]
		Environmental = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c276f9e4-5269-11df-9900-080069138b88", Description="Cultural feature")]
		CulturalFeature = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c2780816-5269-11df-b7b6-080069138b88", Description="Supply")]
		Supply = 6,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c279108a-5269-11df-8bc7-080069138b88", Description="Radio")]
		Radio = 7,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c27a2286-5269-11df-b1d2-080069138b88", Description="Expendable")]
		Expendable = 8,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c27b3144-5269-11df-bb80-080069138b88", Description="Sensor/Emitter")]
		SensorOrEmitter = 9,
	}
}
