//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(314, "Entity Damage Status-Component Identification", 8)]
	public enum EntityDamageStatusComponentIdentification : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("678033cf-2170-44c3-ba24-2f46ee897956", Description="Entity Center (No Specific Component)")]
		EntityCenterNoSpecificComponent = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("114d8211-ccb8-45ff-92bf-4fd279e2c1b0", Description="Entity Structure")]
		EntityStructure = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9ab5275f-f0c6-48ce-84e0-acefb04ff03a", Description="Control System")]
		ControlSystem = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("04e52bc4-7160-434d-b8fc-f5c0e8603b12", Description="Control Surface")]
		ControlSurface = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("dc2761d2-d80c-4d43-9a06-94d15a2f2c1a", Description="Engine / Propulsion System")]
		EngineOrPropulsionSystem = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0714ddaf-4a68-4986-9c09-860608c83dba", Description="Crew Member")]
		CrewMember = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("8e581490-c635-4f26-aa52-e7a5948a6305", Description="Fuse")]
		Fuse = 6,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("4c142fd2-d0cb-4014-b8af-6dac5eecc0d9", Description="Acquisition Sensor")]
		AcquisitionSensor = 7,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("68a46615-2e15-4a71-9c71-44ea81ead9f2", Description="Tracking Sensor")]
		TrackingSensor = 8,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("57ff8c06-48db-43c2-ae77-c186c749dfc9", Description="Fuel Tank / Solid Rocket Motor")]
		FuelTankOrSolidRocketMotor = 9,
	}
}
