//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(324, "Entity Association-Physical Connection Type", 8)]
	public enum EntityAssociationPhysicalConnectionType : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("09642541-a295-42ea-beb7-91dbda36edbd", Description="Not Specified")]
		NotSpecified = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("50f91abe-3632-41aa-ae5d-e88a63c3c3dc", Description="Attached Directly to Surface")]
		AttachedDirectlyToSurface = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("bf36bacb-6c09-401b-9607-b3d905f9c5a0", Description="Cable Wire")]
		CableWire = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c371231c-21e7-4653-a648-ec5f5b22d294", Description="Rope")]
		Rope = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("7be497cb-ad34-4bdd-8d8a-b33a52997802", Description="Chain")]
		Chain = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0ba520e9-d853-4c41-8191-10bd24854881", Description="Power Line")]
		PowerLine = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("98e4e7e9-06a2-499f-b908-ff7a431ddf7b", Description="Telephone Line")]
		TelephoneLine = 6,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("8e7437c8-0497-4e8f-805e-04c951b13d87", Description="Cable Line")]
		CableLine = 7,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ec2ae800-7370-4b27-954e-bdb807ee1830", Description="Refueling Drogue")]
		RefuelingDrogue = 8,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("58c45833-113a-4ce5-a42f-532f3b7e5c93", Description="Refueling Boom")]
		RefuelingBoom = 9,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("b1d2636e-c68d-48b8-962e-6856fa11c8a0", Description="Handcuffs")]
		Handcuffs = 10,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c8ff37b9-2290-485d-bb2c-5c8b5efc4393", Description="In Contact With")]
		InContactWith = 11,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("7b3052e2-7b86-47a8-ba23-8938df9806ae", Description="Fast Rope")]
		FastRope = 12,
	}
}
