//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(55, "Entity Capabilities", 32)]
	public enum EntityCapabilities : uint {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("450d5d35-9c5a-4849-b40b-bc9ce39ecd8c", Description="Land Platform Entity Capabilities")]
		LandPlatformEntityCapabilities = 0u,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("bb4a20ab-dc35-4f2b-a962-8828f179cfb3", Description="Air Platform Entity Capabilities")]
		AirPlatformEntityCapabilities = 1u,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9b2c78db-d8ee-4714-afc0-5c9299e21fbb", Description="Surface Platform Entity Capabilities")]
		SurfacePlatformEntityCapabilities = 2u,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("3c0831bd-7603-43db-bb9f-fd401f7aeff7", Description="Subsurface Platform Entity Capabilities")]
		SubsurfacePlatformEntityCapabilities = 3u,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("3a428314-1bd3-45e6-a90d-c6fab7547dfd", Description="Space Platform Entity Capabilities")]
		SpacePlatformEntityCapabilities = 4u,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("94367335-4423-40f3-a614-660f2c91d497", Description="Munition Entity Capabilities")]
		MunitionEntityCapabilities = 5u,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("61ed7585-6633-4bea-939b-7807c64bf09f", Description="Life Forms Entity Capabilities")]
		LifeFormsEntityCapabilities = 6u,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("bcf2bd67-2f91-4266-a4c6-213067b63517", Description="Environmental Entity Capabilities")]
		EnvironmentalEntityCapabilities = 7u,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("dd75cbcf-72a6-46e5-b516-e931b52057d6", Description="Cultural Feature Entity Capabilities")]
		CulturalFeatureEntityCapabilities = 8u,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("92b31db9-d808-496d-8b01-f4f3571f3b2a", Description="Supply Entity Capabilities")]
		SupplyEntityCapabilities = 9u,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("f55faa1b-a8dd-4e88-ab48-a66bceb23105", Description="Radio Entity Capabilities")]
		RadioEntityCapabilities = 10u,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("09f87f85-a5cb-46f6-8f7d-c7669a32274c", Description="Expendable Entity Capabilities")]
		ExpendableEntityCapabilities = 11u,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("fc5c4252-dc0b-4a4a-b0df-f0ad38cca594", Description="Sensor/Emitter Entity Capabilities")]
		SensorOrEmitterEntityCapabilities = 12u,
	}
}
