//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(27, "Expendable-Subsurface Category", 8)]
	public enum ExpendableSubsurfaceCategory : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c42b920e-5269-11df-8af9-080069138b88", Description="Other")]
		Other = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c42ca0ea-5269-11df-9d49-080069138b88", Description="Active emitter")]
		ActiveEmitter = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c42dab66-5269-11df-ad8c-080069138b88", Description="Passive decoy")]
		PassiveDecoy = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("6ba6f4fb-ab6a-497c-89fa-79c5c67783ad", Description="Signal")]
		Signal = 7,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("f70473b4-b113-445c-897f-47efda5622c9", Description="Noise-Maker Decoy")]
		NoiseMakerDecoy = 9,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("510784bb-a79c-492b-a660-c83d778c32b4", Description="Bubble-Maker Decoy")]
		BubbleMakerDecoy = 10,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("b5a9d666-d92d-4a41-b739-7e66e5e35da2", Description="Multi-Mode Decoy")]
		MultiModeDecoy = 11,
	}
}
