//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(25, "Expendable-Air Category", 8)]
	public enum ExpendableAirCategory : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c41d716a-5269-11df-b612-080069138b88", Description="Other")]
		Other = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c41e82e4-5269-11df-afb1-080069138b88", Description="Chaff")]
		Chaff = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c41f8a86-5269-11df-ab6e-080069138b88", Description="Flare")]
		Flare = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4209926-5269-11df-b9d1-080069138b88", Description="Combined Chaff and Flare")]
		CombinedChaffAndFlare = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c421ac44-5269-11df-8d61-080069138b88", Description="Active Emitter")]
		ActiveEmitter = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c422b580-5269-11df-b3a6-080069138b88", Description="Passive Decoy")]
		PassiveDecoy = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c423c240-5269-11df-9206-080069138b88", Description="Winged Decoy")]
		WingedDecoy = 6,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("afa56982-2364-48ea-9ed7-ec3bf0aaa3da", Description="Signal/Illumination Flare")]
		SignalOrIlluminationFlare = 7,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("f3296d3a-5b5f-431b-8d3c-ea3f2545a58a", Description="Smoke Generator")]
		SmokeGenerator = 8,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d778a22e-fb17-426a-b567-62384d7b1ebe", Description="Combined Flare and Smoke Generator")]
		CombinedFlareAndSmokeGenerator = 12,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ce242f5f-e1da-4923-b52f-76cbeb6112b3", Description="SAR Night Light (SRNL)")]
		SARNightLightSRNL = 13,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("27ffdb0b-3ea6-494a-9c11-39689918f12c", Description="SAR Buoy")]
		SARBuoy = 14,
	}
}
