//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(363, "Format Type", 5)]
	public enum FormatType : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c99db78b-10a4-4eae-b420-cf1ecd1a1a8b", Description="No Data")]
		NoData = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("bf0e844f-a3ce-4927-bd05-05fc3112ed68", Description="Identity Format")]
		IdentityFormat = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("b86714bb-eede-4384-a694-53b576e646da", Description="Surface Format, 5 meter RNP")]
		SurfaceFormat5MeterRNP = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("13ae1667-ef1a-4d0b-9bdc-c9cd2b43d77a", Description="Surface Format, 100 meter RNP")]
		SurfaceFormat100MeterRNP = 6,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("edda0041-57dd-4852-a19a-59e0c52b6d82", Description="Airborne Format, 5 meter RNP, 25-foot Barometric Altitude")]
		AirborneFormat5MeterRNP25FootBarometricAltitude = 7,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("98259531-8d9b-46ec-bb25-e26507d938ba", Description="Airborne Format, 100 meter RNP, 25-foot Barometric Altitude")]
		AirborneFormat100MeterRNP25FootBarometricAltitude = 8,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("004eb5e7-4223-4961-8494-f43b8af8cc59", Description="Airborne Format, 0.25 nmi RNP, 25-foot Barometric Altitude")]
		AirborneFormat0_25NmiRNP25FootBarometricAltitude = 9,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("3c9294a3-d80e-492d-976f-05de6ea578d5", Description="Airborne Format, 1.0 nmi RNP, 25-foot Barometric Altitude")]
		AirborneFormat1_0NmiRNP25FootBarometricAltitude = 10,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("f4d8a449-35ea-41cf-b0c5-4c2b0cf0d0ed", Description="Airborne Format, 5 meter RNP, 100-foot Barometric Altitude")]
		AirborneFormat5MeterRNP100FootBarometricAltitude = 11,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c945ec99-9c1e-44a5-ac39-34014672c0eb", Description="Airborne Format, 100 meter RNP, 100-foot Barometric Altitude")]
		AirborneFormat100MeterRNP100FootBarometricAltitude = 12,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("62efb8f3-0dce-4e42-8f6c-0814bfd41f16", Description="Airborne Format, 0.25 nmi RNP, 100-foot Barometric Altitude")]
		AirborneFormat0_25NmiRNP100FootBarometricAltitude = 13,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("f2c0658e-b7c5-4cc6-82c7-ca503e9554e5", Description="Airborne Format, 1.0 nmi RNP, 100-foot Barometric Altitude")]
		AirborneFormat1_0NmiRNP100FootBarometricAltitude = 14,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("71744e65-ba41-40a2-aa12-28f017c783f1", Description="Airborne Format, 5 meter RNP, GPS Height")]
		AirborneFormat5MeterRNPGPSHeight = 15,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ae49c1fa-4387-4100-93bf-892ffc23cddc", Description="Airborne Format, 100 meter RNP, GPS Height")]
		AirborneFormat100MeterRNPGPSHeight = 16,
	}
}
