//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(297, "High Fidelity HAVE QUICK-TOD Transmit Indicator", 8)]
	public enum HighFidelityHAVEQUICKTODTransmitIndicator : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("408195e5-4105-4dc7-b802-c6896bf7fb2b", Description="No TOD Is Being Transmitted")]
		NoTODIsBeingTransmitted = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("67f3a87d-96d3-4f63-9d48-11234fd7610e", Description="TOD Transmission in Progress")]
		TODTransmissionInProgress = 1,
	}
}
