//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(96, "IFF-Alternate Mode 4 Challenge/Reply", 8)]
	public enum IFFAlternateMode4ChallengeOrReply : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("170c56e8-526a-11df-947e-080069138b88", Description="No Statement")]
		NoStatement = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("170d67d6-526a-11df-9b25-080069138b88", Description="Valid")]
		Valid = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("170e71da-526a-11df-b209-080069138b88", Description="Invalid")]
		Invalid = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("170f8160-526a-11df-a8e0-080069138b88", Description="No response")]
		NoResponse = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d3ccf534-4e2d-4195-89b0-ae389af6ea5f", Description="Unable to Verify")]
		UnableToVerify = 4,
	}
}
