//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(84, "IFF-System Mode", 8)]
	public enum IFFSystemMode : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("165e232a-526a-11df-8fe4-080069138b88", Description="No Statement")]
		NoStatement = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("81343ec9-804d-48ac-954b-8129b808c4c5", Description="Off")]
		Off = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("5fb4ab24-9491-4517-b380-839a20e7d056", Description="Standby")]
		Standby = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0859059d-d61c-426d-87d8-b131fc451222", Description="Normal")]
		Normal = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e02cabcd-82ce-4809-9f6b-14d7ba5f535f", Description="Emergency")]
		Emergency = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("61d8c9da-1791-4852-a6be-5185537623b9", Description="Low or Low Sensitivity")]
		LowOrLowSensitivity = 5,
	}
}
