//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(181, "Intercom Control-Communications Type", 7)]
	public enum IntercomControlCommunicationsType : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1a0704f6-526a-11df-a098-080069138b88", Description="Reserved")]
		Reserved = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1a081602-526a-11df-92ff-080069138b88", Description="Connection FDX")]
		ConnectionFDX = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1a092754-526a-11df-80d4-080069138b88", Description="Connection HDX - Destination is Receive Only")]
		ConnectionHDXDestinationIsReceiveOnly = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1a0a39d2-526a-11df-9599-080069138b88", Description="Connection HDX - Destination is Transmit Only")]
		ConnectionHDXDestinationIsTransmitOnly = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1a0b47c8-526a-11df-9f9c-080069138b88", Description="Connection HDX")]
		ConnectionHDX = 4,
	}
}
