//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(180, "Intercom Control-Control Type", 8)]
	public enum IntercomControlControlType : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19ff64da-526a-11df-a2c5-080069138b88", Description="Reserved")]
		Reserved = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1a006fc4-526a-11df-84c7-080069138b88", Description="Status")]
		Status = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1a01804e-526a-11df-b7b9-080069138b88", Description="Request - Acknowledge Required")]
		RequestAcknowledgeRequired = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1a0291a0-526a-11df-8bef-080069138b88", Description="Request - No Acknowledge")]
		RequestNoAcknowledge = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1a039d70-526a-11df-8e82-080069138b88", Description="Ack - Request Granted")]
		AckRequestGranted = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1a04acba-526a-11df-9b1b-080069138b88", Description="Nack - Request Denied")]
		NackRequestDenied = 5,
	}
}
