//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(416, "Intercom Control-Communications Class", 1)]
	public enum IntercomControlCommunicationsClass : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("30b1f1ff-91f3-4962-b474-2d3a9377ce1e", Description="Simulated Communications Channel")]
		SimulatedCommunicationsChannel = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("143cdd8f-2a98-43bc-b372-fd696468a8f2", Description="Simulation Support Communications Channel")]
		SimulationSupportCommunicationsChannel = 1,
	}
}
