//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(292, "IO Effects Record-IO Effect", 8)]
	public enum IOEffectsRecordIOEffect : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("af54c542-d035-440e-b337-9b260e1989d3", Description="No Statement")]
		NoStatement = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("81dc0fba-5f60-4507-b7cd-720ccf922d74", Description="Denial")]
		Denial = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ec128248-ac04-41da-b096-b57b44ecd354", Description="Degradation")]
		Degradation = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d608f467-0a89-42d5-8416-0030233c2be1", Description="Disruption")]
		Disruption = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9ff21b16-e55c-4382-8615-f5b4b2ca1645", Description="Terminate Effect")]
		TerminateEffect = 255,
	}
}
