//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(715, "Island Subcategory", 16)]
	public enum IslandSubcategory : ushort {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d75580ff-0042-46aa-a4fa-dde054bdd49d", Description="Other")]
		Other = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("05526281-ba82-4a65-ac11-038255f77702", Description="Islands 1,000-2,499 km2 (386-965 sq mi)")]
		Islands10002499Km2386965SqMi = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("564676e3-cda2-4a28-bb30-82ffe5888307", Description="Islands 2,500-4,999 km2 (965-1,930 sq mi)")]
		Islands25004999Km29651930SqMi = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("dc6d8893-b32c-496a-9f46-cc5126faee26", Description="Islands 5,000-9,999 km2 (1,931-3,861 sq mi)")]
		Islands50009999Km219313861SqMi = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("685b8a76-3fe4-4949-90aa-fc840bcc45d9", Description="Islands 10,000-24,999 km2 (3,861-9,652 sq mi)")]
		Islands1000024999Km238619652SqMi = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d30bc580-7dbd-409d-8d79-a273c8bfef3d", Description="Islands 25,000-99,999 km2 (9,653-38,610 sq mi)")]
		Islands2500099999Km2965338610SqMi = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("10d02d96-ee66-46c7-ad03-a94264d45d82", Description="Islands 100,000 km2 (39,000 sq mi) and Greater")]
		Islands100000Km239000SqMiAndGreater = 6,
	}
}
