//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(212, "IsPartOf-Station Name", 16)]
	public enum IspartofStationName : ushort {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b5f5c36-526a-11df-9086-080069138b88", Description="Other")]
		Other = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b606bb2-526a-11df-9317-080069138b88", Description="Aircraft Wingstation")]
		AircraftWingstation = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b617cfa-526a-11df-a816-080069138b88", Description="Ship\'s Forward Gunmount (Starboard)")]
		ShipsForwardGunmountStarboard = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b62904a-526a-11df-a4e4-080069138b88", Description="Ship\'s Forward Gunmount (Port)")]
		ShipsForwardGunmountPort = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b639bb6-526a-11df-b41f-080069138b88", Description="Ship\'s Forward Gunmount (Centerline)")]
		ShipsForwardGunmountCenterline = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b64b0e6-526a-11df-bd8c-080069138b88", Description="Ship\'s Aft Gunmount (Starboard)")]
		ShipsAftGunmountStarboard = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b65c238-526a-11df-a9ef-080069138b88", Description="Ship\'s Aft Gunmount (Port)")]
		ShipsAftGunmountPort = 6,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b66ce76-526a-11df-82fb-080069138b88", Description="Ship\'s Aft Gunmount (Centerline)")]
		ShipsAftGunmountCenterline = 7,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b67e220-526a-11df-8868-080069138b88", Description="Forward Torpedo Tube")]
		ForwardTorpedoTube = 8,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b68f28c-526a-11df-8238-080069138b88", Description="Aft Torpedo Tube")]
		AftTorpedoTube = 9,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b69fe48-526a-11df-a232-080069138b88", Description="Bomb Bay")]
		BombBay = 10,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b6b0da6-526a-11df-8eeb-080069138b88", Description="Cargo Bay")]
		CargoBay = 11,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b6c1c1e-526a-11df-8e7b-080069138b88", Description="Truck Bed")]
		TruckBed = 12,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b6d2a64-526a-11df-aee4-080069138b88", Description="Trailer Bed")]
		TrailerBed = 13,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b6e3bde-526a-11df-8d87-080069138b88", Description="Well Deck")]
		WellDeck = 14,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b6f5488-526a-11df-bc4e-080069138b88", Description="On Station Range and Bearing")]
		OnStationRangeAndBearing = 15,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b706350-526a-11df-9371-080069138b88", Description="On Station xyz")]
		OnStationXyz = 16,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("efabc4f6-38e8-4e02-85ba-031795d3d4bf", Description="Air-to-Air Refueling Boom")]
		AirToAirRefuelingBoom = 17,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("69814ee1-0c7e-4416-b5a0-020f11a74920", Description="Aerial Refueling Receptacle")]
		AerialRefuelingReceptacle = 18,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("75ef48ae-feb4-48e2-8375-6bea588048db", Description="Port Side Refueling Drogue")]
		PortSideRefuelingDrogue = 19,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("16eb4737-74c7-4f2b-a780-02a53c21feca", Description="Starboard Side Refueling Drogue")]
		StarboardSideRefuelingDrogue = 20,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("8e4cedcb-856e-47ce-a284-59b08b34300e", Description="Center Refueling Drogue")]
		CenterRefuelingDrogue = 21,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("10ea3ea1-bcf4-444f-b11f-37d97e7cf131", Description="Air Refueling Probe")]
		AirRefuelingProbe = 22,
	}
}
