//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(516, "Life Form-Human-Specific-Machine Guns", 8)]
	public enum LifeFormHumanSpecificMachineGuns : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("79046a09-4cec-48aa-8fad-5aab87dd268c", Description="Other")]
		Other = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e9a5aeaa-5997-4b99-99fa-948c5623b56c", Description="5.56x45mm XM214 Microgun Six-Pak")]
		_5_56X45mmXM214MicrogunSixPak = 10,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("515bf0e6-4cf8-4e94-bf6e-efab5697843e", Description="7.62x51mm M134/XM196 Minigun")]
		_7_62X51mmM134OrXM196Minigun = 11,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("fb062a35-9eed-4b18-9425-d33014b6541e", Description="5.56x45mm M249/FN Minimi SAW/LMG")]
		_5_56X45mmM249OrFNMinimiSAWOrLMG = 20,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("71296c76-43ef-4571-97b2-942108e39137", Description="5.56x45mm FN Minimi Mk3 LMG")]
		_5_56X45mmFNMinimiMk3LMG = 21,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9a5043c5-b34a-41f8-a338-46b989ba5bd3", Description="7.62x51mm FN Minimi 7.62 Mk3 GPMG")]
		_7_62X51mmFNMinimi7_62Mk3GPMG = 22,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("8b52642a-3f50-48eb-9932-58e56cba07c1", Description="7.62x63mm M1941 Johnson")]
		_7_62X63mmM1941Johnson = 25,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("8ddb9b20-3100-493f-9d59-02310b211886", Description="7.62x63mm M1918 BAR")]
		_7_62X63mmM1918BAR = 26,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("adfefc35-cbe0-4f8a-879e-977b46f27212", Description="7.62x51mm M1919A4/Mk 21 Mod 0 Browning MMG")]
		_7_62X51mmM1919A4OrMk21Mod0BrowningMMG = 27,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ad72a3f8-fba1-41a2-a4c9-f3a0be431da0", Description="7.62x63mm M1919A6 Browning MMG")]
		_7_62X63mmM1919A6BrowningMMG = 28,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("db6e09de-e05a-47b0-89a0-b69f1292e305", Description="7.62x51mm M37 Browning MMG")]
		_7_62X51mmM37BrowningMMG = 29,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("190db131-ecd6-4b20-85dc-3d0c40890a23", Description="5.56x45mm Ares Shrike 5.56 LMG")]
		_5_56X45mmAresShrike5_56LMG = 30,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("a40bd78b-a5f6-4079-8e66-934cbbf1e262", Description="5.56x45mm LSAT LMG")]
		_5_56X45mmLSATLMG = 31,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e06442d6-62f5-4ff5-8e63-771e949c5056", Description="5.56x45mm CMG-1 LMG")]
		_5_56X45mmCMG1LMG = 32,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("27774205-fddd-422a-ba4c-d44eb800f418", Description="5.56x45mm CMG-2 LMG")]
		_5_56X45mmCMG2LMG = 33,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("14913ed5-4fff-4647-badf-61c4fd3d5116", Description="5.56x45mm Stoner 63A LMG")]
		_5_56X45mmStoner63ALMG = 34,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("7d236fa2-4a82-4f22-ad91-42e090c18b62", Description="5.56x45mm Ultimax 100 LMG")]
		_5_56X45mmUltimax100LMG = 35,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("003e72d6-1251-4a20-aa44-26f087b20197", Description="5.56x54mm Beretta AS70/90 LMG")]
		_5_56X54mmBerettaAS70Or90LMG = 36,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e0dcad66-9722-42bb-9fce-416a8f7b0395", Description="5.56x45mm CETME Ameli LMG")]
		_5_56X45mmCETMEAmeliLMG = 37,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("4375bd0d-a456-436a-9b5f-0978c9ef7064", Description="5.56x45mm IMI Negev LMG")]
		_5_56X45mmIMINegevLMG = 38,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1d1910b6-db01-4204-b595-8e310c24edc5", Description="5.56x45mm INSAS LMG")]
		_5_56X45mmINSASLMG = 39,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("5ebf6ace-30a4-4420-b694-c2dca74fdad8", Description="5.56x45mm AUG LMG")]
		_5_56X45mmAUGLMG = 40,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("45d23a65-cda9-42f4-9ed7-4515175d0c2b", Description="5.56x45mm AUG HBAR LMG")]
		_5_56X45mmAUGHBARLMG = 41,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("639e4f56-53f5-432d-853d-1e66fb5bf3fb", Description="5.56x45mm HK MG4 LMG")]
		_5_56X45mmHKMG4LMG = 43,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("39b1c38d-9de9-4148-be0a-752ec3ffc3f6", Description="5.56x45mm HK23/GR-9 LMG")]
		_5_56X45mmHK23OrGR9LMG = 44,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("3ddf4ab1-5b39-498d-a7f0-57c4f8bcc426", Description="5.56x45mm M27 IAR SAW")]
		_5_56X45mmM27IARSAW = 46,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("744239a6-3b5e-4693-b95a-7488af70c789", Description="5.56x45mm L86 LSW")]
		_5_56X45mmL86LSW = 47,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d5900050-4205-48a9-8513-a8f7844f7be8", Description="5.56x45mm Daewoo K3 LMG")]
		_5_56X45mmDaewooK3LMG = 48,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("342af016-1e6a-4d6f-b9c3-445c90b9e9f9", Description="5.56x45mm Vector Mini SS GPMG")]
		_5_56X45mmVectorMiniSSGPMG = 49,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("a0f9c9a7-a3b9-462b-a093-c7a16ac18e52", Description="7.62x51mm M60 GPMG")]
		_7_62X51mmM60GPMG = 50,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("5854c6d4-40b3-40d5-8e74-943c4844d11c", Description="7.62x51mm M60E3 GPMG")]
		_7_62X51mmM60E3GPMG = 51,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("65aa66c0-8823-4872-82f3-7e0730692ac0", Description="7.62x51mm M60E4 GPMG")]
		_7_62X51mmM60E4GPMG = 52,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("11fea18a-de45-401f-a14d-ec2d2827415f", Description="7.62x51mm M60E6 GPMG")]
		_7_62X51mmM60E6GPMG = 53,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("6296d923-a753-4a64-96a3-212b0b62486c", Description="7.62x51mm Mark 48 GMPG")]
		_7_62X51mmMark48GMPG = 55,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("6b9f75c1-5201-4b40-a2be-2479f7fbfd64", Description="7.62x51mm M240/FN MAG 58 GPMG")]
		_7_62X51mmM240OrFNMAG58GPMG = 58,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("26829353-f1b2-410c-983d-fb99b6d56d9f", Description="7.62x51mm M240E4/M240B GPMG")]
		_7_62X51mmM240E4OrM240BGPMG = 59,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0ebdfa2e-b28e-4db4-acff-c81067bdc98e", Description="7.62x51mm M240E1/M240D GPMG")]
		_7_62X51mmM240E1OrM240DGPMG = 60,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("b95efb10-5878-461b-a18e-dddf20db77c8", Description="7.62x51mm M240G GPMG")]
		_7_62X51mmM240GGPMG = 61,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ef45871c-ee72-437a-9e44-11576f219b69", Description="7.62x51mm M240E5/M240H GPMG")]
		_7_62X51mmM240E5OrM240HGPMG = 62,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e2be3e4f-d839-4a2b-b0f8-0b8df84cda18", Description="7.62x51mm M240L GPMG")]
		_7_62X51mmM240LGPMG = 63,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("b4a107b8-6476-4272-b809-98c327f1cf48", Description="7.62x39mm Kk 62 LMG")]
		_7_62X39mmKk62LMG = 65,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0e79264f-9eb7-41f8-95ff-24dc217023e9", Description="7.62x51mm Vector SS-77 GPMG")]
		_7_62X51mmVectorSS77GPMG = 70,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("5f47f5e9-9723-4e81-9b37-75721ce84a2d", Description="7.62x51mm SIG MG 710-3 GPMG")]
		_7_62X51mmSIGMG7103GPMG = 71,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("93f68113-c702-4c31-93f3-96c825f8bffd", Description="7.62x51mm Sterling 7.62 GMPG")]
		_7_62X51mmSterling7_62GMPG = 72,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("639ca6d7-ee07-42e5-b5c1-3b08c58cff67", Description="7.62x51mm Sumitomo Type-62 GPMG")]
		_7_62X51mmSumitomoType62GPMG = 73,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("5af73fe4-bf3d-4381-855b-ecbea6c0ceb1", Description="7.62x51mm Daewoo K12 GPMG")]
		_7_62X51mmDaewooK12GPMG = 74,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("6dd09815-f864-438d-aa37-3a850a8573a9", Description="7.62x51mm MG 51 GPMG")]
		_7_62X51mmMG51GPMG = 75,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d2a78f60-e771-43a2-a4e3-eac1386ba0aa", Description="7.62x51mm Rheinmetall MG 3")]
		_7_62X51mmRheinmetallMG3 = 76,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0dfa01a9-49ba-47ac-9701-41f86c182b76", Description="7.62x51mm Rheinmetall MG 3KWS")]
		_7_62X51mmRheinmetallMG3KWS = 77,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("08dad603-2720-43af-a9ad-c11b9c399428", Description="7.62x51mm MG5/HK121 GPMG")]
		_7_62X51mmMG5OrHK121GPMG = 80,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("31508f2c-0b39-4799-bccf-c2715eeec0f9", Description="7.62x51mm HK21 GPMG")]
		_7_62X51mmHK21GPMG = 81,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d4c7ada2-1c8a-4461-95dc-a8499307b345", Description="7.62x51mm AA-52 GPMP")]
		_7_62X51mmAA52GPMP = 85,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("59d49a63-cd36-40d9-94a7-a6229bf7441b", Description="7.62x51mm UKM-2000 GPMG")]
		_7_62X51mmUKM2000GPMG = 86,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("8ac8dd30-5fea-470c-aed4-c8a4061d91f2", Description="7.62x54mm Uk vz. 59 GPMG")]
		_7_62X54mmUkVz59GPMG = 88,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("39c8e172-98ca-418f-a6c5-a7303e8bfa5f", Description="7.92x57mm MG 42 GPMG")]
		_7_92X57mmMG42GPMG = 89,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ddc6d500-557c-416c-baff-f7664ee1750f", Description="12.7x99mm M2A1 Browning HMG")]
		_12_7X99mmM2A1BrowningHMG = 100,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("14c400f9-a1b4-4f5c-aa9f-c4b89f9075c5", Description="12.7x99mm M2HB Browning HMG")]
		_12_7X99mmM2HBBrowningHMG = 101,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e9447baf-f6fd-473f-b543-727bf9f89d1c", Description="12.7x99mm M2HB-QCB Browning HMG")]
		_12_7X99mmM2HBQCBBrowningHMG = 102,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("4ae503da-9913-4082-861b-a4768e144152", Description="12.7x99mm M85C HMG")]
		_12_7X99mmM85CHMG = 105,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5239bae-1844-4cf2-b116-dea582f98d84", Description="12.7x99mm Rheinmetall RMG.50 HMG")]
		_12_7X99mmRheinmetallRMG50HMG = 108,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("559c1940-1b4a-4296-b9cc-ba3ef0f099ac", Description="12.7x99mm HK25 HMG")]
		_12_7X99mmHK25HMG = 110,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("3889dbf9-8d9b-4e96-ba66-b710415a4310", Description="12.7x99mm CIS 50MG")]
		_12_7X99mmCIS50MG = 112,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("221f0d6a-3248-4bd7-b562-85e0e02dd611", Description="5.45x39mm IP-2 LMG")]
		_5_45X39mmIP2LMG = 120,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("bbec4eda-9cfa-40f1-b2ef-1615ceb6e545", Description="5.45x39mm Nikonov LMG")]
		_5_45X39mmNikonovLMG = 121,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e46a8d41-a0de-4545-b990-a04864ee32a1", Description="5.45x39mm M74 RPK")]
		_5_45X39mmM74RPK = 122,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0f41ad68-1692-4813-a105-95ddd8077f8d", Description="7.62x39mm M43 RPK")]
		_7_62X39mmM43RPK = 125,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("30c7d589-d6a0-4f22-a923-6ab8bc91f108", Description="7.62x39mm RPD SAW")]
		_7_62X39mmRPDSAW = 126,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("25cdb359-e0d8-45ba-bff5-6d651ac9481a", Description="7.62x39mm Zastava M72")]
		_7_62X39mmZastavaM72 = 127,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("5d2ad0ff-3e5b-45dd-8a18-2edd6de7ca7e", Description="7.62x39mm Type-81 LMG")]
		_7_62X39mmType81LMG = 128,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("a3a298bb-53ab-462f-8dfc-e64311258f24", Description="7.62x51mm Zastava M77")]
		_7_62X51mmZastavaM77 = 135,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9f865c1a-fef0-4147-9f4a-2e7f2e3f6b25", Description="7.62x54mm PK GPMG")]
		_7_62X54mmPKGPMG = 140,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4825be2-cd6a-45f3-9556-25ac2cb54a17", Description="7.62x54mm AEK-999 GPMP")]
		_7_62X54mmAEK999GPMP = 141,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("3e8944c9-850f-47cc-bc98-105728859b01", Description="7.62x54mm Pecheneg GPMG")]
		_7_62X54mmPechenegGPMG = 142,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c1586364-8afe-46e0-a697-ec65b7341f94", Description="7.62x54mm Zastava M84")]
		_7_62X54mmZastavaM84 = 143,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("4e3020db-fbdb-4b01-a94c-2f2386ddd14c", Description="7.62x54mm Type-67 GPMG")]
		_7_62X54mmType67GPMG = 144,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("a0ebd137-c28d-4304-8c8b-acc331c1b78e", Description="7.62x54mm Type-80 GPMG")]
		_7_62X54mmType80GPMG = 145,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("678d1818-2caf-4a12-8604-970f031dcbef", Description="12.7x108mm NSV HMG")]
		_12_7X108mmNSVHMG = 150,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9173caea-87d0-4937-8ee6-63bbcac139e3", Description="12.7x108mm Kord HMG")]
		_12_7X108mmKordHMG = 151,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("81d6f99a-b004-451d-a4a9-49453fff0705", Description="12.7x108mm KPD-12.7 HMG")]
		_12_7X108mmKPD12_7HMG = 152,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9b18bac1-918f-46fb-b2b2-5730fbbd7593", Description="12.7x108mm Zastava M02 Coyotoe HMG")]
		_12_7X108mmZastavaM02CoyotoeHMG = 153,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("aeee1a28-21d6-4012-872e-a910f4963845", Description="12.7x108mm Zastava M87")]
		_12_7X108mmZastavaM87 = 154,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("a0324e8c-e6bc-4bc9-9446-d8ca7008d110", Description="12.7x108mm Type-77 HMG")]
		_12_7X108mmType77HMG = 155,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("67be90dc-4dd9-4bed-9384-97c5b21b0556", Description="12.7x108mm W85 HMG")]
		_12_7X108mmW85HMG = 156,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("526d5d5b-c83d-41e2-b9a5-d1f6021cc2cd", Description="12.7x108mm Type-90 HMG")]
		_12_7X108mmType90HMG = 157,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("32259988-842a-4fd9-af0e-9e635d1f466a", Description="5.8x42mm QJY-88 LMG")]
		_5_8X42mmQJY88LMG = 164,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("7ac75370-a5dc-4865-81bf-5874403e28a5", Description="5.8x42mm QBB-95 DBP87 LMG")]
		_5_8X42mmQBB95DBP87LMG = 165,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("48611934-7b1c-4ffd-a13a-cc5ab1ff0ecc", Description="5.56x45mm QBB-95-1 LMG")]
		_5_56X45mmQBB951LMG = 166,
	}
}
