//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(16, "Life Forms-Subcategory-U.S. Weapons", 8)]
	public enum LifeFormsSubcategoryUSWeapons : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c30e834a-5269-11df-8a4e-080069138b88", Description="Assault machine pistol, KF-AMP")]
		AssaultMachinePistolKFAMP = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c30f941a-5269-11df-9a09-080069138b88", Description="Automatic model 1911A1 .45")]
		AutomaticModel1911A145 = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3109fea-5269-11df-a52a-080069138b88", Description="Combat Master Mark VI .45, Detronics")]
		CombatMasterMarkVI45Detronics = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c311afa2-5269-11df-ba60-080069138b88", Description="De-cocker KP90DC .45")]
		DeCockerKP90DC45 = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c312c45a-5269-11df-b519-080069138b88", Description="De-cocker KP91DC .40")]
		DeCockerKP91DC40 = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c313cf6c-5269-11df-b158-080069138b88", Description="General officer\'s Model 15 .45")]
		GeneralOfficersModel1545 = 6,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c314df7e-5269-11df-8112-080069138b88", Description="Nova 9-mm, LaFrance")]
		Nova9MmLafrance = 7,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c315f2a6-5269-11df-ba23-080069138b88", Description="Personal Defense Weapon MP5K-PDW 9-mm")]
		PersonalDefenseWeaponMP5KPDW9Mm = 8,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3170236-5269-11df-a65a-080069138b88", Description="Silenced Colt .45, LaFrance")]
		SilencedColt45Lafrance = 9,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c318134c-5269-11df-a395-080069138b88", Description="5900-series 9-mm, Smith & Wesson (S&W)")]
		_5900Series9MmSmithAndWessonSAndW = 10,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3192412-5269-11df-8390-080069138b88", Description="M9")]
		M9 = 11,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c31a2c9a-5269-11df-8fe2-080069138b88", Description="Model 1911A1, Springfield Armory")]
		Model1911A1SpringfieldArmory = 12,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c31b3d9c-5269-11df-a954-080069138b88", Description="Model 2000 9-mm")]
		Model20009Mm = 13,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c31c5baa-5269-11df-a4af-080069138b88", Description="P-9 9-mm, Springfield Armory")]
		P99MmSpringfieldArmory = 14,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c31d650e-5269-11df-9d68-080069138b88", Description="P-12 9-mm")]
		P129Mm = 15,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c31e7552-5269-11df-9108-080069138b88", Description="P-85 Mark II 9-mm, Ruger")]
		P85MarkII9MmRuger = 16,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c32026ea-5269-11df-888c-080069138b88", Description="Advanced Combat Rifle 5.56-mm, AAI")]
		AdvancedCombatRifle5_56MmAAI = 17,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3213b8e-5269-11df-bd1c-080069138b88", Description="Commando assault rifle, Model 733 5.56-mm, Colt")]
		CommandoAssaultRifleModel7335_56MmColt = 18,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3226cde-5269-11df-8968-080069138b88", Description="Infantry rifle, Mini-14/20 GB 5.56-mm, Ruger")]
		InfantryRifleMini14Or20GB5_56MmRuger = 19,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c32380ec-5269-11df-9158-080069138b88", Description="Mini-14 5.56-mm, Ruger")]
		Mini145_56MmRuger = 20,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c324952c-5269-11df-aafc-080069138b88", Description="Mini Thirty 7.62-mm, Ruger")]
		MiniThirty7_62MmRuger = 21,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c325a6ba-5269-11df-a796-080069138b88", Description="Semi-automatic model 82A2 .50, Barrett")]
		SemiAutomaticModel82A250Barrett = 22,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c326b2ee-5269-11df-98b3-080069138b88", Description="Sniper Weapon System M24 7.62-mm")]
		SniperWeaponSystemM247_62Mm = 23,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c327c206-5269-11df-878a-080069138b88", Description="Sniping rifle M21, Springfield Armory")]
		SnipingRifleM21SpringfieldArmory = 24,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c328d844-5269-11df-ba25-080069138b88", Description="Sniping rifle M40A1 7.62-mm")]
		SnipingRifleM40A17_62Mm = 25,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c329e2ca-5269-11df-9c51-080069138b88", Description="Sniping rifle M600 7.62-mm")]
		SnipingRifleM6007_62Mm = 26,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c32af322-5269-11df-9743-080069138b88", Description="AR-15 (M16) 5.56-mm")]
		AR15M165_56Mm = 27,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c32c0514-5269-11df-afbb-080069138b88", Description="M1 .30")]
		M130 = 28,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c32d0df6-5269-11df-98bf-080069138b88", Description="M14 7.62-mm, NATO")]
		M147_62MmNATO = 29,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c32e1ed0-5269-11df-bb03-080069138b88", Description="M14 (M1A, M1A1-A1), Springfield Armory")]
		M14M1AM1A1A1SpringfieldArmory = 30,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c32f3112-5269-11df-8dc9-080069138b88", Description="M14K assault rifle, LaFrance")]
		M14KAssaultRifleLafrance = 31,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3303b34-5269-11df-a29d-080069138b88", Description="M16A2 assault rifle 5.56-mm, Colt")]
		M16A2AssaultRifle5_56MmColt = 32,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3314c04-5269-11df-b7c5-080069138b88", Description="M21 7.62-mm, U.S.")]
		M217_62MmUS = 33,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3325f9a-5269-11df-a4bb-080069138b88", Description="M77 Mark II 5.56-mm, Ruger")]
		M77MarkII5_56MmRuger = 34,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c33369b2-5269-11df-9295-080069138b88", Description="M77V 7.62-mm, Ruger")]
		M77V7_62MmRuger = 35,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c33479d8-5269-11df-9788-080069138b88", Description="S-16 7.62 x 36-mm, Grendel")]
		S167_62X36MmGrendel = 36,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3358be8-5269-11df-a125-080069138b88", Description="SAR-8 7.62-mm")]
		SAR87_62Mm = 37,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c336989e-5269-11df-9ef3-080069138b88", Description="SAR-4800 7.62-mm")]
		SAR48007_62Mm = 38,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c338486a-5269-11df-ba5e-080069138b88", Description="Assault carbine M16K, LaFrance")]
		AssaultCarbineM16KLafrance = 39,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3395836-5269-11df-9976-080069138b88", Description="M1 .30")]
		M130_1 = 40,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c33a6910-5269-11df-b5ca-080069138b88", Description="M4 (Model 720) 5.56-mm, Colt")]
		M4Model7205_56MmColt = 41,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c33b80ac-5269-11df-badc-080069138b88", Description="M-900 9-mm, Calico")]
		M9009MmCalico = 42,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c33d329e-5269-11df-a6ef-080069138b88", Description="AC-556F 5.56-mm, Ruger")]
		AC556F5_56MmRuger = 43,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c33e45bc-5269-11df-8b05-080069138b88", Description="M3 .45")]
		M345 = 44,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c33f54f2-5269-11df-bf93-080069138b88", Description="M11, Cobray")]
		M11Cobray = 45,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3405f1e-5269-11df-ad6a-080069138b88", Description="M951 9-mm, Calico")]
		M9519MmCalico = 46,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3417070-5269-11df-b06a-080069138b88", Description="MP5/10 10-mm")]
		MP5Or1010Mm = 47,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3427efc-5269-11df-b5f2-080069138b88", Description="9-mm, Colt")]
		_9MmColt = 48,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3438c84-5269-11df-bb44-080069138b88", Description="Ingram")]
		Ingram = 49,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3453a8e-5269-11df-a1c0-080069138b88", Description="Externally powered (EPG) 7.62-mm, Ares")]
		ExternallyPoweredEPG7_62MmAres = 50,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3464a50-5269-11df-8d28-080069138b88", Description="GECAL 50")]
		GECAL50 = 51,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3475d6e-5269-11df-85ce-080069138b88", Description="General purpose M60 7.62-mm")]
		GeneralPurposeM607_62Mm = 52,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c348681c-5269-11df-ac52-080069138b88", Description="Heavy M2HB-QCB .50, RAMO")]
		HeavyM2HBQCB50RAMO = 53,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c349795a-5269-11df-9bc8-080069138b88", Description="Light assault M60E3 (Enhanced) 7.62-mm")]
		LightAssaultM60E3Enhanced7_62Mm = 54,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c34a8cdc-5269-11df-a47e-080069138b88", Description="Light M16A2 5.56-mm, Colt")]
		LightM16A25_56MmColt = 55,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c34b98f2-5269-11df-899f-080069138b88", Description="Light 5.56-mm, Ares")]
		Light5_56MmAres = 56,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c34ca83c-5269-11df-9ee3-080069138b88", Description="Lightweight M2 .50, RAMO")]
		LightweightM250RAMO = 57,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c34dbb6e-5269-11df-b095-080069138b88", Description="Lightweight assault M60E3 7.62-mm")]
		LightweightAssaultM60E37_62Mm = 58,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c34ec5d6-5269-11df-a35d-080069138b88", Description="Minigun M134 7.62-mm, General Electric")]
		MinigunM1347_62MmGeneralElectric = 59,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c34fd732-5269-11df-89c6-080069138b88", Description="MG system MK19 Mod 3, 40-mm")]
		MGSystemMK19Mod340Mm = 60,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c351004e-5269-11df-bdb5-080069138b88", Description="MG system (or kit) M2HB QCB .50, Saco Defense")]
		MGSystemOrKitM2HBQCB50SacoDefense = 61,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3521164-5269-11df-9fb1-080069138b88", Description="M1919A4 .30-cal, Browning")]
		M1919A430CalBrowning = 62,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c35322f2-5269-11df-8144-080069138b88", Description=".50-cal, Browning")]
		_50CalBrowning = 63,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c354d53e-5269-11df-8d61-080069138b88", Description="Colored-smoke hand grenade M18")]
		ColoredSmokeHandGrenadeM18 = 64,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c355e5b4-5269-11df-a411-080069138b88", Description="Colored-smoke grenades, Federal Laboratories")]
		ColoredSmokeGrenadesFederalLaboratories = 65,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c356f2ba-5269-11df-bb25-080069138b88", Description="Infrared smoke grenade M76")]
		InfraredSmokeGrenadeM76 = 66,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c358043e-5269-11df-8670-080069138b88", Description="Smoke hand grenade AN-M8 HC")]
		SmokeHandGrenadeANM8HC = 67,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3591432-5269-11df-a1be-080069138b88", Description="Delay fragmentation hand grenade M61")]
		DelayFragmentationHandGrenadeM61 = 68,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c35a2c3c-5269-11df-82a6-080069138b88", Description="Delay fragmentation hand grenade M67")]
		DelayFragmentationHandGrenadeM67 = 69,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c35b40f4-5269-11df-94d8-080069138b88", Description="Impact fragmentation hand grenade M57")]
		ImpactFragmentationHandGrenadeM57 = 70,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c35c567e-5269-11df-85b4-080069138b88", Description="Impact fragmentation hand grenade M68")]
		ImpactFragmentationHandGrenadeM68 = 71,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c35d60d2-5269-11df-916d-080069138b88", Description="Incendiary hand grenade AN-M14 TH3")]
		IncendiaryHandGrenadeANM14TH3 = 72,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c35e7206-5269-11df-b9d5-080069138b88", Description="Launcher I-M203 40-mm")]
		LauncherIM20340Mm = 73,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c35f85d8-5269-11df-8669-080069138b88", Description="Launcher M79 40-mm")]
		LauncherM7940Mm = 74,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3608ffa-5269-11df-92a6-080069138b88", Description="Multiple grenade launcher MM-1 40-mm")]
		MultipleGrenadeLauncherMM140Mm = 75,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3623fbc-5269-11df-9806-080069138b88", Description="Multi-shot portable flame weapon M202A2 66-mm")]
		MultiShotPortableFlameWeaponM202A266Mm = 76,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3635604-5269-11df-b74a-080069138b88", Description="Portable ABC-M9-7")]
		PortableABCM97 = 77,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3646602-5269-11df-8211-080069138b88", Description="Portable M2A1-7")]
		PortableM2A17 = 78,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3657060-5269-11df-a24e-080069138b88", Description="Portable M9E1-7")]
		PortableM9E17 = 79,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3672342-5269-11df-9fda-080069138b88", Description="Dragon medium Anti-Armor missile, M47, FGM-77A")]
		DragonMediumAntiArmorMissileM47FGM77A = 80,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3683426-5269-11df-8d5b-080069138b88", Description="Javelin AAWS-M")]
		JavelinAAWSM = 81,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3694500-5269-11df-a6db-080069138b88", Description="Light Anti-Tank Weapon M72 (LAW II)")]
		LightAntiTankWeaponM72LAWII = 82,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c36a54ea-5269-11df-bdda-080069138b88", Description="Redeye, FIM-43, General Dynamics")]
		RedeyeFIM43GeneralDynamics = 83,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c36b6542-5269-11df-8d76-080069138b88", Description="Saber dual-purpose missile system")]
		SaberDualPurposeMissileSystem = 84,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c36c7aae-5269-11df-9c19-080069138b88", Description="Stinger, FIM-92, General Dynamics")]
		StingerFIM92GeneralDynamics = 85,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c36d85f2-5269-11df-8ea1-080069138b88", Description="TOW heavy Anti-Tank weapon")]
		TOWHeavyAntiTankWeapon = 86,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c36f373a-5269-11df-80cf-080069138b88", Description="Bear Trap AP device, Pancor")]
		BearTrapAPDevicePancor = 87,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c370480a-5269-11df-a0d7-080069138b88", Description="Chain Gun automatic weapon EX-34 7.62-mm")]
		ChainGunAutomaticWeaponEX347_62Mm = 88,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3715e20-5269-11df-b914-080069138b88", Description="Close Assault Weapon System (CAWS), AAI")]
		CloseAssaultWeaponSystemCAWSAAI = 89,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3726a68-5269-11df-b746-080069138b88", Description="CAWS, Olin/Heckler and Koch")]
		CAWSOlinOrHecklerAndKoch = 90,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3737ab6-5269-11df-82e2-080069138b88", Description="Crossfire SAM Model 88")]
		CrossfireSAMModel88 = 91,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3748ab4-5269-11df-850d-080069138b88", Description="Dragon and M16")]
		DragonAndM16 = 92,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c37597f6-5269-11df-86c8-080069138b88", Description="Firing port weapon M231, 5.56-mm, Colt")]
		FiringPortWeaponM2315_56MmColt = 93,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c376a876-5269-11df-a484-080069138b88", Description="Foxhole Digger Explosive Kit (EXFODA)")]
		FoxholeDiggerExplosiveKitEXFODA = 94,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c377b8a6-5269-11df-bcc9-080069138b88", Description="Infantry Support Weapon ASP-30 {RM} 30-mm")]
		InfantrySupportWeaponASP30RM30Mm = 95,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c378ce1c-5269-11df-b407-080069138b88", Description="Jackhammer Mk 3-A2, Pancor")]
		JackhammerMk3A2Pancor = 96,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c379e3ec-5269-11df-a137-080069138b88", Description="Light Anti-Armor weapon M136 (AT4)")]
		LightAntiArmorWeaponM136AT4 = 97,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c37af61a-5269-11df-b90b-080069138b88", Description="M26A2")]
		M26A2 = 98,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c37bfe3e-5269-11df-bbb2-080069138b88", Description="Master Key S")]
		MasterKeyS = 99,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c37d32c2-5269-11df-9ee3-080069138b88", Description="Minigun 5.56-mm")]
		Minigun5_56Mm = 100,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c37e5472-5269-11df-93a8-080069138b88", Description="Multipurpose Individual Munition (MPIM), Marquardt")]
		MultipurposeIndividualMunitionMPIMMarquardt = 101,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c37f6d1c-5269-11df-85b0-080069138b88", Description="Multipurpose weapon AT8")]
		MultipurposeWeaponAT8 = 102,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c38080bc-5269-11df-bbb2-080069138b88", Description="Recoilless rifle M40, M40A2, and M40A4; 106-mm")]
		RecoillessRifleM40M40A2AndM40A4106Mm = 103,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c381934e-5269-11df-baf1-080069138b88", Description="Recoilless rifle M67, 90-mm")]
		RecoillessRifleM6790Mm = 104,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3829df2-5269-11df-a0cc-080069138b88", Description="Revolver, SP 101")]
		RevolverSP101 = 105,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c383b002-5269-11df-972b-080069138b88", Description="Revolver, Super Redhawk .44 magnum, Ruger")]
		RevolverSuperRedhawk44MagnumRuger = 106,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c384c64a-5269-11df-99f1-080069138b88", Description="RAW rocket, 140-mm, Brunswick")]
		RAWRocket140MmBrunswick = 107,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c385d0d0-5269-11df-98c5-080069138b88", Description="Rifle-launcher Anti-Armor Munition (RAAM), Olin")]
		RifleLauncherAntiArmorMunitionRAAMOlin = 108,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c386e272-5269-11df-96cf-080069138b88", Description="Rocket launcher M-20 3.5-in")]
		RocketLauncherM203_5In = 109,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c387f694-5269-11df-9a90-080069138b88", Description="Rocket launcher, Enhanced M72 \"E series\" HEAT, 66-mm")]
		RocketLauncherEnhancedM72ESeriesHEAT66Mm = 110,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c38907b4-5269-11df-8834-080069138b88", Description="Selective fire weapon AC-556 5.56-mm, Ruger")]
		SelectiveFireWeaponAC5565_56MmRuger = 111,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c38a1b68-5269-11df-b99a-080069138b88", Description="Selective fire weapon AC-556F 5.56-mm, Ruger")]
		SelectiveFireWeaponAC556F5_56MmRuger = 112,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c38b2ddc-5269-11df-a163-080069138b88", Description="Shotgun M870 Mk 1 (U.S. Marine Corps), Remington")]
		ShotgunM870Mk1USMarineCorpsRemington = 113,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c38c3b1e-5269-11df-b8dd-080069138b88", Description="SMAW Mk 193, 83-mm, McDonnell-Douglas")]
		SMAWMk19383MmMcdonnellDouglas = 114,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c38d5008-5269-11df-b348-080069138b88", Description="SMAW-D: Disposable SMAW")]
		SMAWDDisposableSMAW = 115,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c38e5fde-5269-11df-a057-080069138b88", Description="Squad Automatic Weapon (SAW) M249 5.56-mm")]
		SquadAutomaticWeaponSAWM2495_56Mm = 116,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c38f6b36-5269-11df-977f-080069138b88", Description="Tactical Support Weapon 50/12, .50-cal, Peregrine")]
		TacticalSupportWeapon50Or1250CalPeregrine = 117,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c39080e8-5269-11df-9a2b-080069138b88", Description="Telescoped Ammunition Revolver Gun (TARG) .50-cal, Ares")]
		TelescopedAmmunitionRevolverGunTARG50CalAres = 118,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3919424-5269-11df-ae9e-080069138b88", Description="Ultimate over-under combination, Ciener")]
		UltimateOverUnderCombinationCiener = 119,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3929f68-5269-11df-81c2-080069138b88", Description="M18A1 Claymore mine")]
		M18A1ClaymoreMine = 120,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c393af16-5269-11df-948a-080069138b88", Description="Mortar 81-mm")]
		Mortar81Mm = 121,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c394c20c-5269-11df-a970-080069138b88", Description="Machinegun M240 7.62mm")]
		MachinegunM2407_62Mm = 134,
	}
}
