//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(521, "Life Form-Human-Specific-Recoilless Rifles", 8)]
	public enum LifeFormHumanSpecificRecoillessRifles : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("a02e04c3-f3f4-48aa-9a90-afd8e58ea879", Description="Other")]
		Other = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("07f57922-1e23-4164-816e-9521f178aa70", Description="84mm M136 AT-4 CS")]
		_84MmM136AT4CS = 15,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("573188d5-d810-4979-8e29-ba1d18e7acd6", Description="57mm M18 RR")]
		_57MmM18RR = 20,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("4c695aa7-d351-43f2-80de-72a9354d67fd", Description="75mm M20 RR")]
		_75MmM20RR = 21,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("72bf0b58-80df-439f-af4d-fe7abd68b568", Description="120mm M-28 Davy Crockett")]
		_120MmM28DavyCrockett = 22,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ad7ed2dc-fff1-4c40-8133-90d211ddd95c", Description="155mm M-29 Davy Crockett")]
		_155MmM29DavyCrockett = 23,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1dc11551-b4f7-4767-b785-68118952fd6c", Description="106mm M40 Recoilless Rifle")]
		_106MmM40RecoillessRifle = 24,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("80fc8761-8953-4a96-9abe-de0be4b4c090", Description="82mm M60 RR")]
		_82MmM60RR = 25,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("2bc98ef2-d8e9-49e2-8ebf-ab5acc471e5c", Description="90mm M67 RR")]
		_90MmM67RR = 26,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9c58ab4a-94f6-474a-9cc7-d449472e5186", Description="84mm M1 Carl Gustav")]
		_84MmM1CarlGustav = 30,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("adb9419d-d31b-4885-8f30-3ce6836dab9c", Description="84mm M2 Carl Gustav")]
		_84MmM2CarlGustav = 31,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d66c4fcb-f4d9-4519-89eb-0e33455c9010", Description="84mm M3 Carl Gustav")]
		_84MmM3CarlGustav = 32,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("bcf0aabe-d5bd-4854-a163-5357623f5c92", Description="84mm M4 Carl Gustav")]
		_84MmM4CarlGustav = 33,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0cddf72c-7c98-4c94-bde1-6225b763bcaf", Description="74mm Pansarskott m/68 Miniman")]
		_74MmPansarskottMOr68Miniman = 35,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("a7098714-ad82-474c-b19f-fe9856c90eaf", Description="84mm ALAC")]
		_84MmALAC = 40,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("dddfb66a-5708-4b19-bcaf-310e360014f3", Description="82mm B-10 RR")]
		_82MmB10RR = 45,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("fc7b5cf3-0175-4a26-a87a-c7f5992fdee7", Description="107mm B-11 RR")]
		_107MmB11RR = 46,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ce2a189f-ae36-4015-bfcb-9afec005259d", Description="80mm Breda Folgore")]
		_80MmBredaFolgore = 50,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("db0fb12b-e075-4093-a0c3-f867b82027cb", Description="120mm BAT RR")]
		_120MmBATRR = 55,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("06b2424d-1aed-4bf5-9ae4-1dca5c2831cd", Description="73mm SPG-9 Kopye")]
		_73MmSPG9Kopye = 60,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("38812055-23d6-4317-80db-8a3e17e48ea1", Description="88mm RCL 3.45in")]
		_88MmRCL3_45In = 65,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("be354fdc-5554-46e5-a55d-43130d477312", Description="90mm Pvpj 110")]
		_90MmPvpj110 = 70,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("3f675970-037e-47a7-94f5-3f27e36a1c3f", Description="50mm Jagdfaust")]
		_50MmJagdfaust = 75,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ee857991-ee3b-42a2-b758-fafe5fc0b154", Description="30mm Rheinmetall RMK30")]
		_30MmRheinmetallRMK30 = 80,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("bdfe6977-f9dc-46e7-8db0-c2beb52c0777", Description="88mm 55 S 55 Raikka")]
		_88Mm55S55Raikka = 90,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("2874eb60-033e-4e65-9343-256df0e7471f", Description="95mm 95 S 58-61")]
		_95Mm95S5861 = 91,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("40d1e4cd-0117-4d82-91e6-82d166ee8b86", Description="73mm LG40")]
		_73MmLG40 = 95,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("425bfd3f-d4f6-4027-8779-10cab50f2d3e", Description="105mm LG40")]
		_105MmLG40 = 96,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9ce0dc9d-c760-485e-ad5c-a06cccf6b810", Description="105mm LG42")]
		_105MmLG42 = 97,
	}
}
