//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(517, "Life Form-Human-Specific-Grenade Launching Machine Gun", 8)]
	public enum LifeFormHumanSpecificGrenadeLaunchingMachineGun : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("2f9fd927-c906-4bb5-b555-1d03c7a2bf12", Description="Other")]
		Other = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("177401b2-88a9-43fc-b0f3-99a32a35585c", Description="40x53mm HK GMG")]
		_40X53mmHKGMG = 20,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("fe68b7bc-32a1-4daa-87bc-62cf6201160f", Description="40x53mm Mk47 Striker")]
		_40X53mmMk47Striker = 25,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("631511bc-13c2-4edc-bfb9-8e31d28a48da", Description="40mm M75")]
		_40MmM75 = 26,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("167c24c3-3f39-49c0-8563-b7464e0bda64", Description="40mm M129")]
		_40MmM129 = 27,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("5d874049-303d-4726-aa90-d241049adffa", Description="40x46mm XM 174")]
		_40X46mmXM174 = 28,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("abd4feea-b595-4b03-ab13-87f0d47e3855", Description="40x46mm Mk18 Mod 0")]
		_40X46mmMk18Mod0 = 29,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("441e4d9e-5656-4be6-ab37-e079592d7581", Description="40x53mm Mk19")]
		_40X53mmMk19 = 30,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("f3619af1-cc74-4cfe-94c7-cda3f6b10067", Description="40x46mm Mk20 Mod 0")]
		_40X46mmMk20Mod0 = 31,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("deee88e4-349a-4db6-a906-5c9b8e81941f", Description="30x29mm RAG-30/SAG-30")]
		_30X29mmRAG30OrSAG30 = 40,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("445f29b3-118c-4033-906e-054e11601523", Description="30x29mm AGS-17 Plamya")]
		_30X29mmAGS17Plamya = 41,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ef92870e-1fb8-4bc1-8440-20c05dc9878b", Description="30x29mm AGS-30 Atlant")]
		_30X29mmAGS30Atlant = 42,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("00fe3996-7d6b-4347-9ffb-78d2e10e2a5c", Description="40mm VOG AGS-40 Balkan")]
		_40MmVOGAGS40Balkan = 43,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("44acc1bc-9ae6-4218-b67a-157fc47125af", Description="40x53mm SB LAG 40")]
		_40X53mmSBLAG40 = 44,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5ef449d-f549-4021-8ce5-2f1e28215600", Description="40x53mm Vektor Y3")]
		_40X53mmVektorY3 = 50,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9ee39196-8f79-49b2-8c82-5385961db596", Description="40x53mm CIS 40")]
		_40X53mmCIS40 = 55,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("5428b230-2059-4a60-b57d-f819120c3074", Description="40x56mm Howa Type-96")]
		_40X56mmHowaType96 = 60,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1d29cb98-202a-4b75-b7da-bed9a3911162", Description="40x53mm Daewoo Precision Industries K4")]
		_40X53mmDaewooPrecisionIndustriesK4 = 65,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("a1950e34-02cf-40b0-9561-abb4696cc220", Description="25x59mm XM307 Advanced Crew Served Weapon")]
		_25X59mmXM307AdvancedCrewServedWeapon = 70,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("df11400f-e383-4b14-b41e-fa4b287b30a5", Description="35x32mm QLZ87")]
		_35X32mmQLZ87 = 80,
	}
}
