//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(481, "Life Form-Human-Specific-Sniper", 8)]
	public enum LifeFormHumanSpecificSniper : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("5cd8a280-e023-403f-8e68-c45039b12adb", Description="Other")]
		Other = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ca46335c-fbde-4053-93da-1baf36c58700", Description="5.8mm QBU-88 (Type 88)")]
		_5_8MmQBU88Type88 = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("5291b6db-9189-40b7-95e8-2194399d049e", Description="7.62mm C3")]
		_7_62MmC3 = 30,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("57650166-d1ca-4e72-a686-bc8e0b0a6970", Description="7.62mm FR F2")]
		_7_62MmFRF2 = 31,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0c2e06b6-2454-4898-b396-203fdff3158c", Description="7.62mm AWM-F (G22)")]
		_7_62MmAWMFG22 = 32,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("bd92156c-fef7-490d-80b0-e1c8d5a77d0d", Description="7.62mm G3 SG/1")]
		_7_62MmG3SGOr1 = 33,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("8f6674c4-b9c8-4b90-9801-f99561ca8802", Description="7.62mm Galil Sniper")]
		_7_62MmGalilSniper = 34,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("5094d721-ef00-4586-9fe0-e888024f43fa", Description="7.62mm L96A1")]
		_7_62MmL96A1 = 35,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("4639f331-fef9-4e78-9bed-cebbeaa48712", Description="7.62mm M14 DMR")]
		_7_62MmM14DMR = 36,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("52fedd2c-46e5-4e41-b9e7-0c7bfae4ee94", Description="7.62mm M24 Sniper Weapon System (SWS)")]
		_7_62MmM24SniperWeaponSystemSWS = 37,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ab0ccd5c-902c-40d2-94aa-898ba8917e66", Description="7.62mm M40A1/A3")]
		_7_62MmM40A1OrA3 = 38,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("89aba231-5bda-473f-bcfc-b5d593d0638b", Description="7.62mm Steyr SSG 69")]
		_7_62MmSteyrSSG69 = 39,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("b8beeae2-414b-4ab6-a401-e19762aa28ea", Description="7.62mm SVD (Dragunov)")]
		_7_62MmSVDDragunov = 40,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("894309c9-65a7-431e-8fe2-d0919a1e9d25", Description="7.62mm TYPE 79")]
		_7_62MmTYPE79 = 41,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0f634858-5111-4730-9cbe-b9d95967377d", Description="7.62mm SR-25 MK11")]
		_7_62MmSR25MK11 = 42,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("17846e08-5d6c-41af-8bb8-12729c53af40", Description="7.62mm AW SR-98")]
		_7_62MmAWSR98 = 43,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("4fd2b533-383a-40f0-b406-6eda125b249e", Description="7.62mm Blaser R93")]
		_7_62MmBlaserR93 = 44,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("b0862b0f-a986-4858-9694-9c6c9b0fe078", Description="7.7mm TYPE 99")]
		_7_7MmTYPE99 = 100,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("74e0791e-931e-469e-a126-c087fdf4edde", Description="8.58mm Blaser R93 Tactical 2")]
		_8_58MmBlaserR93Tactical2 = 105,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("441d5078-9a69-4f8e-9554-5b29397067dd", Description="9mm VSS Vintorez")]
		_9MmVSSVintorez = 110,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("46eb3ac3-b797-47cc-a7d5-64ea584391e2", Description="12.7mm Steyr HS .50")]
		_12_7MmSteyrHS50 = 170,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4e87a65-0dd7-4d6f-a52c-6056952fa043", Description="12.7mm M82A1A Special Applications Scoped Rifle (SASR)")]
		_12_7MmM82A1ASpecialApplicationsScopedRifleSASR = 171,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("223ffe5a-44cf-431d-81ca-f793db284f27", Description="12.7mm NSV")]
		_12_7MmNSV = 172,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ebb742da-abb1-45cb-96d6-7c29d852e792", Description="12.7mm OSV-96")]
		_12_7MmOSV96 = 173,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9f949187-3935-43c0-9cac-1386ce53055d", Description="12.7mm Rangemaster 50")]
		_12_7MmRangemaster50 = 174,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d380234a-a6c6-4904-9807-1bdb17582e74", Description="12.7mm V94")]
		_12_7MmV94 = 175,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("f3ea42fc-0148-4af4-9ccd-24a439ab91f9", Description="20mm Denel NTW-20")]
		_20MmDenelNTW20 = 200,
	}
}
