//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(522, "Life Form-Human-Specific-Flame Rockets", 8)]
	public enum LifeFormHumanSpecificFlameRockets : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("03f540ff-245a-4b39-af9a-207d82f3c677", Description="Other")]
		Other = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("34a3c184-9cd4-4798-9b8f-c146e86003a9", Description="66mm M202 Flash")]
		_66MmM202Flash = 20,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("cba8d47f-e739-4a7a-bc0f-e8386dbb1295", Description="62mm FHJ-84")]
		_62MmFHJ84 = 30,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("7f936067-9e82-4314-b3ea-ae9335aa06f6", Description="90mm C90-CR-FIM (M3)")]
		_90MmC90CRFIMM3 = 40,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("eb088016-2e8a-4aca-a49b-a1b7793dfc13", Description="93mm RPO-A Shmel")]
		_93MmRPOAShmel = 50,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d62f2b95-e7e6-413a-af3c-2b9a039802c6", Description="93mm RPO-Z Shmel")]
		_93MmRPOZShmel = 51,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1e32274e-a3a1-4f08-b84d-361f4bdca127", Description="93mm RPO-D Shmel")]
		_93MmRPODShmel = 52,
	}
}
