//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(18, "Life Forms-Subcategory-U.K. Weapons", 8)]
	public enum LifeFormsSubcategoryUKWeapons : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3cf4738-5269-11df-a67c-080069138b88", Description="LAW 80")]
		LAW80 = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3d054e8-5269-11df-b165-080069138b88", Description="Blowpipe")]
		Blowpipe = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3d15c9e-5269-11df-8a01-080069138b88", Description="Javelin")]
		Javelin = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3d26b5c-5269-11df-ad31-080069138b88", Description="51-mm mortar")]
		_51MmMortar = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3d37e20-5269-11df-8b8f-080069138b88", Description="SLR 7.62-mm rifle")]
		SLR7_62MmRifle = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3d49148-5269-11df-9115-080069138b88", Description="Sterling 9-mm submachine gun")]
		Sterling9MmSubmachineGun = 6,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3d5a18c-5269-11df-b50d-080069138b88", Description="L7A2 general purpose MG")]
		L7A2GeneralPurposeMG = 7,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3d6b338-5269-11df-9fea-080069138b88", Description="L6 Wombat Recoilless rifle,")]
		L6WombatRecoillessRifle = 8,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3d7c17e-5269-11df-a3f3-080069138b88", Description="Carl Gustav 89-mm recoilless rifle")]
		CarlGustav89MmRecoillessRifle = 9,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3d8f1b6-5269-11df-86d3-080069138b88", Description="SA80 Individual/light support weapon")]
		SA80IndividualOrLightSupportWeapon = 10,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3da086c-5269-11df-8346-080069138b88", Description="Trigat")]
		Trigat = 11,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3db11e4-5269-11df-968c-080069138b88", Description="Milan AT missile")]
		MilanATMissile = 12,
	}
}
