//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(740, "Link 11B Data Signaling Rate", 8)]
	public enum Link11BDataSignalingRate : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("579d5a4b-091c-4f84-ad3b-4dc864a8c3ba", Description="No Statement")]
		NoStatement = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("2ea361bf-a0b9-4446-835a-4c6fc074f70a", Description="Not Used")]
		NotUsed = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("a3828f43-70b4-4ca2-a23e-bda350978291", Description="Not Used")]
		NotUsed_1 = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c3dd5247-111a-4f2e-b3ee-b52784407b5f", Description="1200 bps")]
		_1200Bps = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("4f21f2a4-6c53-4f24-961f-123cf3497041", Description="2400 bps")]
		_2400Bps = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("31ce792b-2376-4259-a926-906c795d4451", Description="600 bps")]
		_600Bps = 5,
	}
}
