//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(733, "Link 11 Signal Integration Interval", 8)]
	[System.ObsoleteAttribute("UID table only for historical purposes. Do not add new entries")]
	public enum Link11SignalIntegrationInterval : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("16c2e0a1-5f15-44a6-9a03-33027889874c", Description="No Statement")]
		[System.ObsoleteAttribute()]
		NoStatement = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("f8ed2f63-4b31-4ea1-8f1e-301570d8222d", Description="9 ms")]
		[System.ObsoleteAttribute()]
		_9Ms = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("2b78e579-cb87-4d34-b492-22c9e61f8662", Description="18 ms")]
		[System.ObsoleteAttribute()]
		_18Ms = 2,
	}
}
