//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(738, "Link 11B Mode of Operation", 16)]
	public enum Link11BModeOfOperation : ushort {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("8b0bb164-9b76-46ad-bca9-015c50c8db67", Description="No Statement")]
		NoStatement = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("557f0409-9db9-4ee2-a9d2-816abe316151", Description="Full Transmission of Data")]
		FullTransmissionOfData = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("10f85e82-05bc-4866-8bfd-30fdac00c3c9", Description="Limited Transmission of Data")]
		LimitedTransmissionOfData = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("58af6457-fb2b-4353-b38b-e9c78cff96b7", Description="Receive only")]
		ReceiveOnly = 3,
	}
}
