//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(734, "Link 11 Signal Waveform", 8)]
	public enum Link11SignalWaveform : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("04a3370c-6563-4021-8921-c54a0ee7eb51", Description="No Statement - CLEW Format")]
		NoStatementCLEWFormat = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("7cbffc06-2f47-439e-8787-647b5294c3c6", Description="Conventional Link Eleven Waveform (CLEW)")]
		ConventionalLinkElevenWaveformCLEW = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("fb19d6de-08e3-4851-af9e-11e53bc5b7a9", Description="Single Tone Link Eleven Waveform (SLEW)")]
		SingleToneLinkElevenWaveformSLEW = 2,
	}
}
