//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(466, "Material", 4)]
	public enum Material : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("7737f739-8b37-49e1-9cc4-f4d977bf5a59", Description="Not Specified")]
		NotSpecified = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("48ae85b5-0f90-4083-b5a9-6a3c343444fc", Description="Plastic")]
		Plastic = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("30ecc495-0c7b-48d9-adf9-3d99a506b691", Description="Rubber")]
		Rubber = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9c47ee46-a465-4ebc-8252-b13f71e21a81", Description="Road")]
		Road = 3,
	}
}
