//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(425, "Minefield Paint Scheme-Paint Scheme", 6)]
	public enum MinefieldPaintSchemePaintScheme : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1aee41ae-526a-11df-929d-080069138b88", Description="Other")]
		Other = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1af0e558-526a-11df-a2b9-080069138b88", Description="Standard")]
		Standard = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1af1fe52-526a-11df-9d56-080069138b88", Description="Camouflage Desert")]
		CamouflageDesert = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1af313a0-526a-11df-bdbd-080069138b88", Description="Camouflage Jungle")]
		CamouflageJungle = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1af42952-526a-11df-90b0-080069138b88", Description="Camouflage Snow")]
		CamouflageSnow = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1af5440e-526a-11df-b9dd-080069138b88", Description="Camouflage Gravel")]
		CamouflageGravel = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1af64ef8-526a-11df-85e6-080069138b88", Description="Camouflage Pavement")]
		CamouflagePavement = 6,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1af7616c-526a-11df-aa69-080069138b88", Description="Camouflage Sand")]
		CamouflageSand = 7,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1af87688-526a-11df-a936-080069138b88", Description="Natural Wood")]
		NaturalWood = 8,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1af9828a-526a-11df-8bcf-080069138b88", Description="Clear")]
		Clear = 9,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1afa91d4-526a-11df-9ef9-080069138b88", Description="Red")]
		Red = 10,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1afba394-526a-11df-b4d5-080069138b88", Description="Blue")]
		Blue = 11,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1afcb2ac-526a-11df-bfe3-080069138b88", Description="Green")]
		Green = 12,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1afdc2aa-526a-11df-8101-080069138b88", Description="Olive")]
		Olive = 13,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1afed212-526a-11df-a810-080069138b88", Description="White")]
		White = 14,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1affde46-526a-11df-a138-080069138b88", Description="Tan")]
		Tan = 15,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b00f236-526a-11df-aaa1-080069138b88", Description="Black")]
		Black = 16,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b0200e0-526a-11df-b1b8-080069138b88", Description="Yellow")]
		Yellow = 17,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1b030b16-526a-11df-ae87-080069138b88", Description="Brown")]
		Brown = 18,
	}
}
