//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(355, "Mode S Squitter Record Source", 1)]
	public enum ModeSSquitterRecordSource : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("f5177e81-8506-43b5-9837-ac1346bc6c10", Description="Layer 4 IFF Data Records")]
		Layer4IFFDataRecords = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("5bf82715-e088-4c76-b954-2a0038d93b7f", Description="Layer 5 GICB IFF Data Records")]
		Layer5GICBIFFDataRecords = 1,
	}
}
