//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(354, "Mode S Squitter Type", 3)]
	public enum ModeSSquitterType : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("91aabf09-b84f-49d6-b4d9-86a17377a311", Description="Not Capable")]
		NotCapable = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("cb6585a8-2715-45c7-b282-6b96f13918b1", Description="Acquisition")]
		Acquisition = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("827c3dd4-01d6-4f26-a001-6e0b528cf2fe", Description="Extended")]
		Extended = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("6508f603-d148-474c-9f53-6db1a2a41f67", Description="Short")]
		Short = 3,
	}
}
