//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(448, "Platform-Surface Other Vessels Subcategories", 8)]
	public enum PlatformSurfaceOtherVesselsSubcategories : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("b771b2ac-7ca0-416c-bc3a-9649e6a3726a", Description="Go-Fast Boat")]
		GoFastBoat = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("4bddb901-f199-4f80-bfee-555a4178903d", Description="Research Vessel")]
		ResearchVessel = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("8ee41b04-766d-4d16-8837-229b81f54214", Description="Hydrofoil Vessel")]
		HydrofoilVessel = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("55b6cda2-f7e2-4fc7-8f3e-73b961babb05", Description="Cable Layer Vessel")]
		CableLayerVessel = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("8510e307-5a48-4907-80f8-9ab68b0fc2e1", Description="Dredger Vessel")]
		DredgerVessel = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("8b6cc6d2-021d-4b6f-afba-0f0bfa5019c0", Description="Junk/Dhow Vessel")]
		JunkOrDhowVessel = 6,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d495a8c2-fcff-4ca9-a0f9-859602522f57", Description="Catamaran")]
		Catamaran = 7,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("60a26360-aead-4e90-a4dd-1c26762cc457", Description="Pontoon")]
		Pontoon = 8,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d369c5d9-e342-4521-ac0d-5bef402ef891", Description="Personal Water Craft")]
		PersonalWaterCraft = 9,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ddb35eb5-a0ac-455d-b698-97331b190075", Description="Refugee Raft")]
		RefugeeRaft = 10,
	}
}
