//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(279, "Platform-Air Civilian Lighter than Air, Balloon Subcategories", 8)]
	public enum PlatformAirCivilianLighterThanAirBalloonSubcategories : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c470b8ab-25fb-495f-b8b3-9ccf250cc5da", Description="Gas-filled, free")]
		GasFilledFree = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("719b5016-e8e7-454b-861f-8157919cb876", Description="Gas-filled, tethered")]
		GasFilledTethered = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9a053980-2712-4ec9-856a-0822f3b76407", Description="Hot Air")]
		HotAir = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("75e6963d-ac1b-409f-ad26-30153b12fc17", Description="Roziere Balloon")]
		RoziereBalloon = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("386b97c3-bde5-470d-97b5-8e4bef798820", Description="Helikite")]
		Helikite = 5,
	}
}
