//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(439, "Platform-Land-Trains Subcategories", 8)]
	public enum PlatformLandTrainsSubcategories : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("13240370-a72f-48d1-b275-d063f3f855ca", Description="Other")]
		Other = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("59321a83-f9c6-4b4d-b437-b73786772585", Description="Engine (Locomotive)")]
		EngineLocomotive = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("27797bc3-08f5-45ce-8eeb-3f509f18f605", Description="Box Car")]
		BoxCar = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c223b99e-804c-4ca6-8939-f293ae9ef28a", Description="Tanker")]
		Tanker = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("81c8cdf3-0389-4cee-b934-d09a4d670711", Description="Flatcar")]
		Flatcar = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ba8217c1-e2fc-4810-a72d-b7f4117def57", Description="Caboose")]
		Caboose = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("8dfea412-bf4a-4700-9858-a8b8d0795796", Description="Passenger Car")]
		PassengerCar = 6,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("6fcf2c15-cc16-44e8-816d-d3a7ed5fc3dd", Description="Hopper")]
		Hopper = 7,
	}
}
