//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(434, "Platform-Land-Construction Specialty Vehicle Subcategories", 8)]
	public enum PlatformLandConstructionSpecialtyVehicleSubcategories : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d4a8fdbe-0db7-4564-a13b-caf78806e9a5", Description="Other")]
		Other = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("f8943a5e-ca86-4069-9da0-54948ec28991", Description="Tug")]
		Tug = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("b87b4419-13b8-4da4-a5b1-c77022e5e47f", Description="Forklift")]
		Forklift = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("b61ea801-3259-44e4-83fe-3975097c83d4", Description="Loader")]
		Loader = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("53017913-3815-4d18-82e0-8222b0535466", Description="Loader, Backhoe")]
		LoaderBackhoe = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c7e748fd-f51b-4b8f-8163-1fea7c813ce4", Description="Crane, Tractor Mounted")]
		CraneTractorMounted = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9e1777d3-81c9-4a12-a6cf-30fedf594107", Description="Crane, Wheeled")]
		CraneWheeled = 6,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("28cde882-2a97-41a8-a620-410fb588fa42", Description="Grader")]
		Grader = 7,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("66cbaf67-5559-406d-9d9e-7e9c2b56b3a1", Description="Road Roller, Other")]
		RoadRollerOther = 8,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("93af86c0-9f2c-47ca-b26b-24dccbdc51e4", Description="Road Roller, Double Drum, Smooth")]
		RoadRollerDoubleDrumSmooth = 9,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("921fccf9-2c88-4bae-b9ec-d701eb3709e0", Description="Road Roller, Single Drum, Smooth")]
		RoadRollerSingleDrumSmooth = 10,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("7b6bf162-cc1f-4855-9f54-ba428a615a59", Description="Road Roller, Double Drum, Sheeps")]
		RoadRollerDoubleDrumSheeps = 11,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("aa0910a8-0fee-4811-b7fa-4bd377f167fc", Description="Road Roller, Single Drum, Sheeps")]
		RoadRollerSingleDrumSheeps = 12,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9c8059ab-3c27-4d76-a815-9ee9ade0f934", Description="Road Roller, Pneumatic Tired")]
		RoadRollerPneumaticTired = 13,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("aaf0a30b-e091-43bb-98d3-2a491365818e", Description="Excavator, Other")]
		ExcavatorOther = 14,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("36a32ffe-ebbf-4920-9b82-b7f1b0c39c45", Description="Excavator, Dragline")]
		ExcavatorDragline = 15,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("de554405-dfa8-471e-883a-8db8b207ab8e", Description="Excavator, Long Reach")]
		ExcavatorLongReach = 16,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c385cb7c-3383-4aa7-96e5-85dad24ec416", Description="Excavator, Mobile Tire")]
		ExcavatorMobileTire = 17,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("bf90b1ff-4120-4a35-aa62-1ba8db6f2f0e", Description="Mini Excavator")]
		MiniExcavator = 18,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e446a51f-aa9c-4fd6-befd-17653e9a050a", Description="Excavator Giant")]
		ExcavatorGiant = 19,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0beddc65-820a-4c57-afe9-1a6ceb4af2d7", Description="Bulldozer, Tractor Mounted")]
		BulldozerTractorMounted = 20,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d1f3275c-f514-417c-b36c-52cced0fe909", Description="Bulldozer, Tracked")]
		BulldozerTracked = 21,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("bc18744c-8849-4253-900d-0288e3334992", Description="Scraper")]
		Scraper = 22,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ed2148b9-8d5d-49f1-9983-f1bde60dbcd0", Description="Skid Steer")]
		SkidSteer = 23,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19483bfe-a3cc-47df-b72b-a38edf86d0ff", Description="Dump Truck, Other")]
		DumpTruckOther = 24,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("a650d8c7-4203-4479-a862-ce2285cf31f9", Description="Dump Truck, Articulated")]
		DumpTruckArticulated = 25,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("10500e56-69f6-4d81-b987-cca36678eb06", Description="Dump Truck, Transfer")]
		DumpTruckTransfer = 26,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("154417de-295c-41af-9909-70cfc597a4ed", Description="Dump Truck, Super")]
		DumpTruckSuper = 27,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c91debc8-b252-41f2-966e-43fac7774185", Description="Dump Truck, Off Road")]
		DumpTruckOffRoad = 28,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("7d2318cb-9e78-49ce-911c-f3963ae7079a", Description="Paver")]
		Paver = 29,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("b2785709-4e57-45ee-9b13-416e3fa78531", Description="Drilling Machine")]
		DrillingMachine = 30,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("367dc1b6-166c-4fac-803b-fa8ade6f065a", Description="Concrete Mixer, Other")]
		ConcreteMixerOther = 31,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("2bbbe6e1-753f-4687-8e15-6e21948f8602", Description="Concrete Mixer, Rear Discharge")]
		ConcreteMixerRearDischarge = 32,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("3a211845-83b1-4a03-a9da-eef2546b7fdd", Description="Concrete Mixer, Front Discharge")]
		ConcreteMixerFrontDischarge = 33,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0e640e4a-ee1c-4ac9-810a-f65ca0e04740", Description="Concrete Mixer, Six Axle")]
		ConcreteMixerSixAxle = 34,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e5546deb-2b7f-4838-8aca-e6cbb4e3f186", Description="Concrete Mixer, Long Reach Boom")]
		ConcreteMixerLongReachBoom = 35,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("95f9d83d-9825-477a-8c1a-ba75ab87fdd4", Description="Concrete Mixer, Volumetric")]
		ConcreteMixerVolumetric = 36,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1df0bbb0-5df5-4a3c-ac03-bc13bb5e7cbe", Description="Trencher, Chain")]
		TrencherChain = 37,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0881918d-3e0c-4c1a-95a5-513ee641bc76", Description="Trencher, Rockwheel")]
		TrencherRockwheel = 38,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("5cc53ab1-f307-44a3-b6f5-afc04f4cc116", Description="Snowcat")]
		Snowcat = 39,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("13217eac-311d-4c07-a860-cce6288acf47", Description="Crane, Tracked")]
		CraneTracked = 40,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("197ef74b-c926-467a-bc59-fee27c6af25d", Description="Crane, Shovel")]
		CraneShovel = 41,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("f4c0cad4-a094-4a91-90f7-cc6e4f16cc3b", Description="Sweeper, Rotary")]
		SweeperRotary = 42,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ff05a7f3-e8e0-4ce5-affa-5803b8eacb2f", Description="Roller, Vibratory Compactor")]
		RollerVibratoryCompactor = 43,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("599f9cad-12a7-4b2c-b8fe-7b8ab4a9b910", Description="Fork Lift, Truck")]
		ForkLiftTruck = 44,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("b4dcd0fa-77d5-4ecc-b0cd-788559144e94", Description="Fork Lift, Rought Terrain")]
		ForkLiftRoughtTerrain = 45,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("3a86e83c-b247-4c69-a53d-be40f847a3c2", Description="Transloader")]
		Transloader = 46,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("98b6e14b-b952-432c-acb0-0bdbbab50d29", Description="Truck, Water, Construction")]
		TruckWaterConstruction = 47,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d19d66cf-5516-4951-8f50-21da22ea0a0a", Description="Truck, Fuel Delivery")]
		TruckFuelDelivery = 48,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0f644dc6-8b2c-495c-a6b4-a4698daa61b1", Description="Truck, Sawmill")]
		TruckSawmill = 49,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e0289c9c-56f5-4df8-a4c6-6d02bb408e0f", Description="Truck, Line Marking, Construction")]
		TruckLineMarkingConstruction = 50,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c906da0f-9f86-4af4-9326-f870c2ad2c34", Description="Tractor, Industrial")]
		TractorIndustrial = 51,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("203aa425-4c0d-435e-badc-dd88a0c3688c", Description="Compactor, High Speed")]
		CompactorHighSpeed = 52,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("667ebb9a-5c57-4ea3-9855-640ffcf33210", Description="Truck, Drilling")]
		TruckDrilling = 53,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0f8ef659-6477-4540-bc91-13254b6a051e", Description="Truck, Drilling Support")]
		TruckDrillingSupport = 54,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("a6a91f5e-00f1-4021-bef8-c458e650ec5f", Description="Crane, Construction")]
		CraneConstruction = 55,
	}
}
