//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(275, "Platform-Air Civilian Ultralight Rigid Wing Aircraft Subcategories", 8)]
	public enum PlatformAirCivilianUltralightRigidWingAircraftSubcategories : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d34359b8-72c7-41ed-b5e2-793750cbc389", Description="Weight-shift control")]
		WeightShiftControl = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("5722ad3f-289c-4508-b5c1-dd2ce9b3da7b", Description="Control surface (elevator, rudder, aileron) control")]
		ControlSurfaceElevatorRudderAileronControl = 2,
	}
}
