//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(441, "Platform-Surface-Passenger Vessel Subcategories", 8)]
	public enum PlatformSurfacePassengerVesselSubcategories : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("4c3a21a7-3aed-44bc-bb2e-c2895d99164d", Description="Cruise Ship")]
		CruiseShip = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("2453d9e5-5b99-4912-9541-67bb58e2dae5", Description="Cruise Ferry")]
		CruiseFerry = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("95008bef-bc63-4058-8c2c-2a1b0511072a", Description="High Speed Ferry")]
		HighSpeedFerry = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e14b70b6-1c1c-4cb6-8082-95581ae3ffc9", Description="Ferry")]
		Ferry = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("00a87ad6-eaba-4e51-8e55-abe9d8b85036", Description="Ocean Liner")]
		OceanLiner = 5,
	}
}
