//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(274, "Platform-Air Civilian Ultralight Non-rigid Wing Aircraft Subcategories", 8)]
	public enum PlatformAirCivilianUltralightNonRigidWingAircraftSubcategories : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("40883567-efd6-401e-a618-1cde1bfcb04f", Description="Hang Glider, Unpowered")]
		HangGliderUnpowered = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("56964888-94ee-440c-88cf-b63e332d5f39", Description="Hang Glider, Powered")]
		HangGliderPowered = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ba736912-c0dd-4e86-83a7-80812eb2f8f5", Description="Paraglider, Unpowered")]
		ParagliderUnpowered = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1e4ee3de-578b-4fec-a3e6-dc561d6720e7", Description="Paraglider, Powered")]
		ParagliderPowered = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("387e995c-02c9-4bb1-bfba-0f5171b4a1ae", Description="Powered Parachute")]
		PoweredParachute = 5,
	}
}
