//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(28, "Sensor/Emitter Category", 8)]
	public enum SensorOrEmitterCategory : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c43000c8-5269-11df-925f-080069138b88", Description="Other")]
		Other = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c43112ec-5269-11df-8705-080069138b88", Description="Multi-spectral")]
		MultiSpectral = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c43221e6-5269-11df-b2e8-080069138b88", Description="RF Active")]
		RFActive = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c433341e-5269-11df-b347-080069138b88", Description="RF Passive (intercept and DF)")]
		RFPassiveInterceptAndDF = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4343ecc-5269-11df-b43b-080069138b88", Description="Optical (direct viewing with or without optics)")]
		OpticalDirectViewingWithOrWithoutOptics = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4357648-5269-11df-80e3-080069138b88", Description="Electro-Optical")]
		ElectroOptical = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4368bc8-5269-11df-a9d4-080069138b88", Description="Seismic")]
		Seismic = 6,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4379662-5269-11df-9e48-080069138b88", Description="Chemical, point detector")]
		ChemicalPointDetector = 7,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c438a728-5269-11df-9baa-080069138b88", Description="Chemical, standoff")]
		ChemicalStandoff = 8,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c439b5f0-5269-11df-87cb-080069138b88", Description="Thermal (temperature sensing)")]
		ThermalTemperatureSensing = 9,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c43ac7ce-5269-11df-8333-080069138b88", Description="Acoustic, Active")]
		AcousticActive = 10,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c43bd86c-5269-11df-8261-080069138b88", Description="Acoustic, Passive")]
		AcousticPassive = 11,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c43ce9d2-5269-11df-b548-080069138b88", Description="Contact/Pressure (physical, hydrostatic, barometric)")]
		ContactOrPressurePhysicalHydrostaticBarometric = 12,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c43dfbce-5269-11df-a970-080069138b88", Description="Electro-Magnetic Radiation (gamma radiation)")]
		ElectroMagneticRadiationGammaRadiation = 13,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c43f0e88-5269-11df-b88a-080069138b88", Description="Particle Radiation (Neutrons, alpha, beta particles)")]
		ParticleRadiationNeutronsAlphaBetaParticles = 14,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4402066-5269-11df-b1fb-080069138b88", Description="Magnetic")]
		Magnetic = 15,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c4412b46-5269-11df-89a2-080069138b88", Description="Gravitational")]
		Gravitational = 16,
	}
}
