//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(178, "Signal-TDL Type", 16)]
	public enum SignalTDLType : ushort {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19abe9ae-526a-11df-a253-080069138b88", Description="Other")]
		Other = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19acf5d8-526a-11df-9b41-080069138b88", Description="PADIL")]
		PADIL = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19ae0612-526a-11df-a8ef-080069138b88", Description="NATO Link-1")]
		NATOLink1 = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19af1638-526a-11df-b95d-080069138b88", Description="ATDL-1")]
		ATDL1 = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19b02370-526a-11df-b1dd-080069138b88", Description="Link 11B (TADIL B)")]
		Link11BTADILB = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19b132ba-526a-11df-b4dd-080069138b88", Description="Situational Awareness Data Link (SADL)")]
		SituationalAwarenessDataLinkSADL = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19b2434e-526a-11df-9bd2-080069138b88", Description="Link 16 Legacy Format (JTIDS/TADIL-J)")]
		Link16LegacyFormatJTIDSOrTADILJ = 6,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19b350a4-526a-11df-8578-080069138b88", Description="Link 16 Legacy Format (JTIDS/FDL/TADIL-J)")]
		Link16LegacyFormatJTIDSOrFDLOrTADILJ = 7,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19b4667e-526a-11df-8851-080069138b88", Description="Link 11A (TADIL A)")]
		Link11ATADILA = 8,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19b57500-526a-11df-8e64-080069138b88", Description="IJMS")]
		IJMS = 9,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19b67e3c-526a-11df-a2d3-080069138b88", Description="Link 4A (TADIL C)")]
		Link4ATADILC = 10,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19b7920e-526a-11df-b832-080069138b88", Description="Link 4C")]
		Link4C = 11,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19b8a1a8-526a-11df-b8ba-080069138b88", Description="TIBS")]
		TIBS = 12,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19b9aada-526a-11df-9537-080069138b88", Description="ATL")]
		ATL = 13,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19bab92a-526a-11df-b2c8-080069138b88", Description="Constant Source")]
		ConstantSource = 14,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19bbcd7e-526a-11df-8b66-080069138b88", Description="Abbreviated Command and Control")]
		AbbreviatedCommandAndControl = 15,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19bcd778-526a-11df-b985-080069138b88", Description="MILSTAR")]
		MILSTAR = 16,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19bde7d0-526a-11df-9d33-080069138b88", Description="ATHS")]
		ATHS = 17,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19bf0502-526a-11df-89e0-080069138b88", Description="OTHGOLD")]
		OTHGOLD = 18,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19c0133e-526a-11df-a5cd-080069138b88", Description="TACELINT")]
		TACELINT = 19,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19c122e2-526a-11df-a863-080069138b88", Description="Weapons Data Link (AWW-13)")]
		WeaponsDataLinkAWW13 = 20,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19c23d6c-526a-11df-aaf8-080069138b88", Description="Abbreviated Command and Control")]
		[System.ObsoleteAttribute()]
		AbbreviatedCommandAndControl_1 = 21,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19c348ce-526a-11df-87d6-080069138b88", Description="Enhanced Position Location Reporting System (EPLRS)")]
		EnhancedPositionLocationReportingSystemEPLRS = 22,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19c45d04-526a-11df-8d9a-080069138b88", Description="Position Location Reporting System (PLRS)")]
		PositionLocationReportingSystemPLRS = 23,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19c5723e-526a-11df-b8ec-080069138b88", Description="SINCGARS")]
		SINCGARS = 24,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19c67b52-526a-11df-b00e-080069138b88", Description="Have Quick I")]
		HaveQuickI = 25,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19c789f2-526a-11df-8e4f-080069138b88", Description="Have Quick II")]
		HaveQuickII = 26,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19c89e8c-526a-11df-b194-080069138b88", Description="Have Quick IIA (Saturn)")]
		HaveQuickIIASaturn = 27,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19c9abb0-526a-11df-a37d-080069138b88", Description="Intra-Flight Data Link 1")]
		IntraFlightDataLink1 = 28,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19cabc76-526a-11df-a92d-080069138b88", Description="Intra-Flight Data Link 2")]
		IntraFlightDataLink2 = 29,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19cbcee0-526a-11df-bb5a-080069138b88", Description="Improved Data Modem (IDM)")]
		ImprovedDataModemIDM = 30,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19ccdc7c-526a-11df-8d82-080069138b88", Description="Air Force Application Program Development (AFAPD)")]
		AirForceApplicationProgramDevelopmentAFAPD = 31,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19cdf184-526a-11df-af0d-080069138b88", Description="Cooperative Engagement Capability (CEC)")]
		CooperativeEngagementCapabilityCEC = 32,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19cf02a4-526a-11df-bbb7-080069138b88", Description="Forward Area Air Defense (FAAD) Data Link (FDL)")]
		ForwardAreaAirDefenseFAADDataLinkFDL = 33,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19d01090-526a-11df-a075-080069138b88", Description="Ground Based Data Link (GBDL)")]
		GroundBasedDataLinkGBDL = 34,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19d123fe-526a-11df-82ad-080069138b88", Description="Intra Vehicular Info System (IVIS)")]
		IntraVehicularInfoSystemIVIS = 35,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19d234e2-526a-11df-959a-080069138b88", Description="Marine Tactical System (MTS)")]
		MarineTacticalSystemMTS = 36,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19d33fcc-526a-11df-912f-080069138b88", Description="Tactical Fire Direction System (TACFIRE)")]
		TacticalFireDirectionSystemTACFIRE = 37,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19d4520e-526a-11df-9265-080069138b88", Description="Integrated Broadcast Service (IBS)")]
		IntegratedBroadcastServiceIBS = 38,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19d56784-526a-11df-b470-080069138b88", Description="Airborne Information Transfer (ABIT)")]
		AirborneInformationTransferABIT = 39,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19d6744e-526a-11df-a4f2-080069138b88", Description="Advanced Tactical Airborne Reconnaissance System (ATARS) Data Link")]
		AdvancedTacticalAirborneReconnaissanceSystemATARSDataLink = 40,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19d787f8-526a-11df-9e70-080069138b88", Description="Battle Group Passive Horizon Extension System (BGPHES) Data Link")]
		BattleGroupPassiveHorizonExtensionSystemBGPHESDataLink = 41,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19d89e18-526a-11df-8b0e-080069138b88", Description="Common High Bandwidth Data Link (CHBDL)")]
		CommonHighBandwidthDataLinkCHBDL = 42,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19d9ad44-526a-11df-8541-080069138b88", Description="Guardrail Interoperable Data Link (IDL)")]
		GuardrailInteroperableDataLinkIDL = 43,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19dabfa4-526a-11df-9fc3-080069138b88", Description="Guardrail Common Sensor System One (CSS1) Data Link")]
		GuardrailCommonSensorSystemOneCSS1DataLink = 44,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19dbd1c8-526a-11df-a16e-080069138b88", Description="Guardrail Common Sensor System Two (CSS2) Data Link")]
		GuardrailCommonSensorSystemTwoCSS2DataLink = 45,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19dcdf46-526a-11df-8e2e-080069138b88", Description="Guardrail CSS2 Multi-Role Data Link (MRDL)")]
		GuardrailCSS2MultiRoleDataLinkMRDL = 46,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19ddf584-526a-11df-b5ef-080069138b88", Description="Guardrail CSS2 Direct Air to Satellite Relay (DASR) Data Link")]
		GuardrailCSS2DirectAirToSatelliteRelayDASRDataLink = 47,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19df0a3c-526a-11df-9ed1-080069138b88", Description="Line of Sight (LOS) Data Link Implementation (LOS tether)")]
		LineOfSightLOSDataLinkImplementationLOSTether = 48,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19e01f44-526a-11df-8d85-080069138b88", Description="Lightweight CDL (LWCDL)")]
		LightweightCDLLWCDL = 49,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19e13410-526a-11df-b06d-080069138b88", Description="L-52M (SR-71)")]
		L52MSR71 = 50,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19e244ae-526a-11df-a91a-080069138b88", Description="Rivet Reach/Rivet Owl Data Link")]
		RivetReachOrRivetOwlDataLink = 51,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19e3506a-526a-11df-b40f-080069138b88", Description="Senior Span")]
		SeniorSpan = 52,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19e45e38-526a-11df-b9a3-080069138b88", Description="Senior Spur")]
		SeniorSpur = 53,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19e570ac-526a-11df-8e8c-080069138b88", Description="Senior Stretch.")]
		SeniorStretch = 54,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19e67ad8-526a-11df-ad64-080069138b88", Description="Senior Year Interoperable Data Link (IDL)")]
		SeniorYearInteroperableDataLinkIDL = 55,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19e78cfc-526a-11df-8859-080069138b88", Description="Space CDL")]
		SpaceCDL = 56,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19e8a056-526a-11df-935b-080069138b88", Description="TR-1 mode MIST Airborne Data Link")]
		TR1ModeMISTAirborneDataLink = 57,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19e9ac44-526a-11df-b0bd-080069138b88", Description="Ku-band SATCOM Data Link Implementation (UAV)")]
		KuBandSATCOMDataLinkImplementationUAV = 58,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19eabe18-526a-11df-8b4e-080069138b88", Description="Mission Equipment Control Data link (MECDL)")]
		MissionEquipmentControlDataLinkMECDL = 59,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19ebd3a2-526a-11df-8702-080069138b88", Description="Radar Data Transmitting Set Data Link")]
		RadarDataTransmittingSetDataLink = 60,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19ece1c0-526a-11df-95da-080069138b88", Description="Surveillance and Control Data Link (SCDL)")]
		SurveillanceAndControlDataLinkSCDL = 61,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19edf402-526a-11df-9e37-080069138b88", Description="Tactical UAV Video")]
		TacticalUAVVideo = 62,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19ef0586-526a-11df-b4a1-080069138b88", Description="UHF SATCOM Data Link Implementation (UAV)")]
		UHFSATCOMDataLinkImplementationUAV = 63,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19f01340-526a-11df-9d01-080069138b88", Description="Tactical Common Data Link (TCDL)")]
		TacticalCommonDataLinkTCDL = 64,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19f12442-526a-11df-8310-080069138b88", Description="Low Level Air Picture Interface (LLAPI)")]
		LowLevelAirPictureInterfaceLLAPI = 65,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19f23972-526a-11df-a471-080069138b88", Description="Weapons Data Link (AGM-130)")]
		WeaponsDataLinkAGM130 = 66,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19656b0d-9e2a-4176-84a9-b5eef44faae7", Description="Automatic Identification System (AIS)")]
		AutomaticIdentificationSystemAIS = 67,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0933acd7-5d54-480d-9e2e-489b3d2b120c", Description="Weapons Data Link (AIM-120)")]
		WeaponsDataLinkAIM120 = 68,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e4bc3ad7-af0f-4ae9-8d45-c536a1c268da", Description="Weapons Data Link (AIM-9)")]
		WeaponsDataLinkAIM9 = 69,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("a57f301e-0fd8-445b-b51d-8ec252fcd7c7", Description="Weapons Data Link (CAMM)")]
		WeaponsDataLinkCAMM = 70,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19f3433a-526a-11df-810a-080069138b88", Description="GC3")]
		GC3 = 99,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19f453ba-526a-11df-bfaa-080069138b88", Description="Link 16 Standardized Format (JTIDS/MIDS/TADIL J)")]
		Link16StandardizedFormatJTIDSOrMIDSOrTADILJ = 100,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19f56962-526a-11df-895e-080069138b88", Description="Link 16 Enhanced Data Rate (EDR JTIDS/MIDS/TADIL-J)")]
		Link16EnhancedDataRateEDRJTIDSOrMIDSOrTADILJ = 101,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19f67726-526a-11df-b0d8-080069138b88", Description="JTIDS/MIDS Net Data Load (TIMS/TOMS)")]
		JTIDSOrMIDSNetDataLoadTIMSOrTOMS = 102,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19f787ec-526a-11df-a306-080069138b88", Description="Link 22")]
		Link22 = 103,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("19f89880-526a-11df-8c00-080069138b88", Description="AFIWC IADS Communications Links")]
		AFIWCIADSCommunicationsLinks = 104,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("272aee86-3ea3-42d7-897c-6fdb490f5667", Description="F-22 Intra-Flight Data Link (IFDL)")]
		F22IntraFlightDataLinkIFDL = 105,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0b06a970-cac2-4bc4-b4ac-dcf4d6e23f87", Description="L-Band SATCOM")]
		LBandSATCOM = 106,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("8f361577-b030-4891-8775-a146b0b0b126", Description="TSAF Communications Link")]
		TSAFCommunicationsLink = 107,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("cb789e40-675a-4287-a274-e9100f7af761", Description="Enhanced SINCGARS 7.3")]
		EnhancedSINCGARS7_3 = 108,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d2bb69bb-2973-44ce-8384-dfca2b355122", Description="F-35 Multifunction Advanced Data Link (MADL)")]
		F35MultifunctionAdvancedDataLinkMADL = 109,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("398574e1-d5f5-4cb7-9ca1-f8d91bc59bd8", Description="Cursor on Target")]
		CursorOnTarget = 110,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e8fe7cea-c21f-403f-8952-3c5822bb016e", Description="All Purpose Structured Eurocontrol Surveillance Information Exchange (ASTERIX)")]
		AllPurposeStructuredEurocontrolSurveillanceInformationExchangeASTERIX = 111,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("dc4f68e0-ef31-4abb-880e-16dd9948a11c", Description="Variable Message Format (VMF) over Combat Net Radio (VMF over CNR)")]
		VariableMessageFormatVMFOverCombatNetRadioVMFOverCNR = 112,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9771d8aa-94f6-4a84-ae55-55ad8b598ca4", Description="Link 16 Surrogate for Non-NATO TDL")]
		Link16SurrogateForNonNATOTDL = 113,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("5953c2b2-0cda-427f-99a6-03160974cd31", Description="MQ-1/9 C-Band LOS Uplink")]
		MQ1Or9CBandLOSUplink = 114,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("f95750a6-f481-49a7-949c-0ce7d63d3920", Description="MQ-1/9 C-Band LOS Downlink")]
		MQ1Or9CBandLOSDownlink = 115,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0a9ce6c2-1070-46dc-b17d-5313810c3544", Description="MQ-1/9 Ku-Band SATCOM Uplink")]
		MQ1Or9KuBandSATCOMUplink = 116,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("75125d8e-fbd5-4458-b3c8-ef1b2cd5c3eb", Description="MQ-1/9 Ku-Band SATCOM Downlink")]
		MQ1Or9KuBandSATCOMDownlink = 117,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("dae509f3-0982-43ab-bef6-6767e4ce9605", Description="Weapons Datalink (SDB II)")]
		WeaponsDatalinkSDBII = 118,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1f5b355a-a814-4cdf-b4b2-b5614ce9acc5", Description="JTAC SA Uplink")]
		JTACSAUplink = 119,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("80fb0ece-b2c9-45f7-bd1b-6a2bc21d7ca2", Description="Common Interactive Broadcast (CIB)")]
		CommonInteractiveBroadcastCIB = 120,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("43b78ec2-53d3-44aa-a0e0-e4df4ddce757", Description="Joint Range Extension Application Protocol A (JREAP A)")]
		JointRangeExtensionApplicationProtocolAJREAPA = 121,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("16c64c53-8455-4e64-8000-88d18436bb0b", Description="JPALS Data Link")]
		JPALSDataLink = 125,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("52f26df6-51af-4397-b779-b92e81ba50b0", Description="OneSAF IADS Communications Link")]
		OnesafIADSCommunicationsLink = 126,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("95daf178-67b6-4363-855d-d404007de4b9", Description="Tactical Targeting Network Technology (TTNT) Application")]
		TacticalTargetingNetworkTechnologyTTNTApplication = 127,
	}
}
