//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(67, "Stop/Freeze-Reason", 8)]
	public enum StopOrFreezeReason : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0d858612-526a-11df-841a-080069138b88", Description="Other")]
		Other = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0d8693e0-526a-11df-a1c8-080069138b88", Description="Recess")]
		Recess = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0d87a910-526a-11df-b51c-080069138b88", Description="Termination")]
		Termination = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0d88b742-526a-11df-8492-080069138b88", Description="System Failure")]
		SystemFailure = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0d89c6f0-526a-11df-9132-080069138b88", Description="Security Violation")]
		SecurityViolation = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0d8ad6a8-526a-11df-a407-080069138b88", Description="Entity Reconstitution")]
		EntityReconstitution = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0d8bdf8a-526a-11df-8fdb-080069138b88", Description="Stop for reset")]
		StopForReset = 6,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0d8ceeca-526a-11df-be7a-080069138b88", Description="Stop for restart")]
		StopForRestart = 7,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0d8e0300-526a-11df-99c2-080069138b88", Description="Abort Training Return to Tactical Operations")]
		AbortTrainingReturnToTacticalOperations = 8,
	}
}
