//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(121, "Subcategories for Subsurface Category 201 - Mammal", 8)]
	public enum SubcategoriesForSubsurfaceCategory201Mammal : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("a2322359-0e6b-4e17-8b03-4ae64b3835e5", Description="Whale")]
		Whale = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("196f4d02-085f-49eb-b371-a10d4970ea99", Description="Beaked Whale")]
		BeakedWhale = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("a27bd5e8-4dd6-47b8-a26f-d24281fea4e9", Description="Beluga Whale")]
		BelugaWhale = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("f22944da-d4d9-48e9-8a28-f4df1eb492b2", Description="Blue Whale")]
		BlueWhale = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("2b1d9f73-f6ff-4a67-8c4a-a828380c5b1d", Description="Bottlenose Whale")]
		BottlenoseWhale = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0c7c559b-9921-416b-8015-1d78e9be75c7", Description="Northern Bottlenose Whale")]
		NorthernBottlenoseWhale = 6,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("a1870364-6da9-484c-ac17-ef3e147094b8", Description="Southern Bottlenose Whale")]
		SouthernBottlenoseWhale = 7,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("b3823d1f-3861-47e9-851f-7ea631f07888", Description="Bowhead Whale")]
		BowheadWhale = 8,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c025846d-6632-4331-a03c-75c40967bd3a", Description="Bryde\'s Whale")]
		BrydesWhale = 9,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1cd9d3f9-3928-4c65-b178-cc9bb6e09893", Description="Dwarf Sperm Whale")]
		DwarfSpermWhale = 10,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("3336cf3c-a94b-417a-819a-d259adedd4c2", Description="Finback Whale")]
		FinbackWhale = 11,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("13590eec-6765-4e1a-80ca-8dd09fc909e8", Description="Gray Whale")]
		GrayWhale = 12,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("4ac7819a-850d-4396-bd35-cc9c6e20b24e", Description="Humpback Whale")]
		HumpbackWhale = 13,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("25c82f19-f32c-4916-b9b7-f2ebc5a6ed23", Description="Long-Finned Pilot Whale")]
		LongFinnedPilotWhale = 14,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("03a2d204-3841-421a-96cc-ad11e8c5560b", Description="Minke Whale")]
		MinkeWhale = 15,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0420d043-f018-41bb-9947-bc80fd0213fc", Description="Northern Minke Whale")]
		NorthernMinkeWhale = 16,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("61094474-f251-4ba3-bfc5-121c7bee67dc", Description="Southern Minke Whale")]
		SouthernMinkeWhale = 17,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c43dc506-f4a3-4100-8b02-0347b39065b1", Description="Narwhal Whale")]
		NarwhalWhale = 18,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("48b6384a-9436-494e-a1c8-77d9e27f7d9d", Description="Orca Whale")]
		OrcaWhale = 19,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("338b03b4-78d1-4e91-84a6-98c70d4842ad", Description="Pygmy Sperm Whale")]
		PygmySpermWhale = 20,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("84c98cc7-d85d-4b28-8cc8-a597c2aff4af", Description="Right Whale")]
		RightWhale = 21,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("a948de59-e497-4961-a556-e7346d984ea7", Description="North Atlantic Right Whale")]
		NorthAtlanticRightWhale = 22,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("45b74a4b-726c-4ed8-a11c-1155e48d51e9", Description="North Pacific Right Whale")]
		NorthPacificRightWhale = 23,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c862d46d-d10b-4b89-b263-3445d4132818", Description="Southern Right Whale")]
		SouthernRightWhale = 24,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("6613842d-8835-4b98-a731-2f5f1f0d71e8", Description="Sei Whale")]
		SeiWhale = 25,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("b699708a-c9c0-42c0-ad54-5aaa969a83e5", Description="Short-Finned Pilot Whale")]
		ShortFinnedPilotWhale = 26,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9eec4c80-f585-48a8-87ef-606bc22357a3", Description="Sperm Whale")]
		SpermWhale = 27,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e327813e-4ed8-463c-8a0c-0e5b79e32f1e", Description="Dolphin")]
		Dolphin = 50,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c9c9ce5e-f416-411a-b6cf-99c3b541b2e9", Description="Bottlenose Dolphin")]
		BottlenoseDolphin = 51,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d59db7e2-d585-4b67-8a28-c21ad0151bfe", Description="Bottlenose Indo-Pacific Dolphin")]
		BottlenoseIndoPacificDolphin = 52,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("17d6d0ce-51de-41c2-80ec-ea176621499a", Description="Bottlenose Burrunan Dolphin")]
		BottlenoseBurrunanDolphin = 53,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("502df0d7-81a0-471a-931b-c71824642c8a", Description="Atlantic Spotted Dolphin")]
		AtlanticSpottedDolphin = 54,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("43285f0c-9423-4940-b722-1d95df7e4bd9", Description="Australian Snubfin Dolphin")]
		AustralianSnubfinDolphin = 55,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("4fd5caf5-87c2-46ad-ab49-67bb72d1cf87", Description="Chilean Black Dolphin")]
		ChileanBlackDolphin = 56,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ebf02171-0eed-47e6-9e3a-03a01f614040", Description="Chinese White Dolphin")]
		ChineseWhiteDolphin = 57,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("04a727e1-8c39-4dab-8065-f8387a1b5f90", Description="Clymene Dolphin")]
		ClymeneDolphin = 58,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ccb9c926-81af-48ac-b0b8-f3d1c1d34827", Description="Porpoise")]
		Porpoise = 100,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("60985d7b-cd13-4511-9bf2-2b6600baca9e", Description="Harbour Porpoise")]
		HarbourPorpoise = 101,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("c5a72c6c-ab3b-492b-99fe-39e5e090f337", Description="Californian Porpoise")]
		CalifornianPorpoise = 102,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("b9341ef7-5e9d-4261-8f1d-714d271782b2", Description="Dall\'s Porpoise")]
		DallsPorpoise = 103,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("8da6561f-8862-41ed-b65e-98c1173396bd", Description="Burmeister\'s Porpoise")]
		BurmeistersPorpoise = 104,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("a00d22a2-415d-4e08-b876-a02a52d859bd", Description="Seal")]
		Seal = 120,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("46a64203-3c10-4c84-8c77-10222d553742", Description="Bearded Seal")]
		BeardedSeal = 121,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("44a80f15-c589-4ead-ac32-85f63ac70083", Description="Harbor Seal")]
		HarborSeal = 122,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("40128fd0-6e12-423c-9012-b6496feaab28", Description="Fur Seal")]
		FurSeal = 123,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("b03ca6eb-13e3-4d39-a9e8-3e3a4768aaee", Description="Weddell Seal")]
		WeddellSeal = 124,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("81e1f2cc-0dd8-4c61-ac05-8a7015109eee", Description="Elephant Seal")]
		ElephantSeal = 125,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("5f44bee9-0aa8-4369-911c-b2fcd264f7b1", Description="Sea Lion")]
		SeaLion = 130,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("fc52b598-37d8-43a4-8a56-362fdc67be11", Description="Australian Sea Lion")]
		AustralianSeaLion = 131,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("449b2bcb-fdd5-4a20-9595-9b48071b917a", Description="California Sea Lion")]
		CaliforniaSeaLion = 132,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("61da6e8a-ec62-480a-8dad-5422f380f372", Description="Walrus")]
		Walrus = 140,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("7adf1012-1634-44ee-8766-65c5a1f9253b", Description="Atlantic Walrus")]
		AtlanticWalrus = 141,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("bcc411fc-b39a-4361-8e82-c673df8ad5f2", Description="Pacific Walrus")]
		PacificWalrus = 142,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ea4122db-36d4-421d-8403-fcc084f6ad22", Description="Otter")]
		Otter = 150,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("21263c8e-4def-40b2-a4f3-26f4f5c94caa", Description="Sea Otter")]
		SeaOtter = 151,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("95cb1815-61df-4897-b4d9-2314dde8c594", Description="Manatee")]
		Manatee = 160,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1a7d2d5a-f087-4faa-868c-d8c44a094fdc", Description="Florida Manatee")]
		FloridaManatee = 161,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("3952e6b6-5d4b-46f2-908d-d84b4b7bea4f", Description="Dugongs")]
		Dugongs = 162,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("7f467830-5a7d-4768-b8cc-8e6443b239b8", Description="Polar Bear")]
		PolarBear = 200,
	}
}
