//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(102, "Subcategories for Land Category 202 - Amphibian", 8)]
	public enum SubcategoriesForLandCategory202Amphibian : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("fd59966c-925f-4ec1-8a28-95b44ced2436", Description="Frog")]
		Frog = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e38b4419-a75a-4b55-85e0-244e6188a0b1", Description="Toad")]
		Toad = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("b816f381-1146-41c3-b111-4b964b321751", Description="Salamander")]
		Salamander = 170,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9bf57f8e-37ba-4d52-9c8e-f40c39e506b4", Description="Caecilian")]
		Caecilian = 230,
	}
}
