//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(104, "Subcategories for Land Category 204 - Arachnid", 8)]
	public enum SubcategoriesForLandCategory204Arachnid : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e12bf9fa-f493-4635-bf0b-cb2905d0f2b9", Description="Spider")]
		Spider = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e70a3ec5-e7b2-4911-b78f-7fc124d6e7ce", Description="Tick")]
		Tick = 20,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d24e07f2-2c92-44d3-bd95-194f3237bdf5", Description="Scorpion")]
		Scorpion = 30,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d876bca3-2edb-4d41-b2f4-1ac811c26176", Description="Harvestmen")]
		Harvestmen = 40,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("fbc24644-d6a7-4edd-bc30-d6ba386e5283", Description="Mite")]
		Mite = 50,
	}
}
