//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(103, "Subcategories for Land Category 203 - Insect", 8)]
	public enum SubcategoriesForLandCategory203Insect : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("706f177d-5869-4bde-857a-53ffccdbd77c", Description="Beetle")]
		Beetle = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("bed7d530-80c1-42f5-b0dd-6a5014e32f67", Description="Mantis")]
		Mantis = 60,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e888d0d2-af86-48f1-9895-4d0eb36a7de2", Description="Cockroach")]
		Cockroach = 70,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e2f51199-bdff-4660-a2a8-22debafc50d1", Description="Army Ant")]
		ArmyAnt = 80,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("fa3ad727-efff-4248-aa22-fec82e923745", Description="Fire Ant")]
		FireAnt = 81,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("8dbcbec9-4bea-494a-911f-ed1d5fd38953", Description="Grasshopper")]
		Grasshopper = 90,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d4ffa1d1-aae4-4baf-b7f6-af5a3db3c8da", Description="Centipede")]
		Centipede = 100,
	}
}
