//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(120, "Subcategories for Subsurface Category 200 - Fish", 8)]
	public enum SubcategoriesForSubsurfaceCategory200Fish : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("42e544a2-7422-45da-ba41-9395ec72c044", Description="Forage Fish, Small Schooling")]
		ForageFishSmallSchooling = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("18900259-77a3-4504-96f7-6fba0914442f", Description="Herring")]
		Herring = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("3e04499b-6b3c-408e-a184-7d03e75cb6ed", Description="Sardines")]
		Sardines = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("04427f37-18a4-4ca0-bd86-15e09635dfa6", Description="Krill")]
		Krill = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("f4d343f1-1530-438a-9874-34bea25e8af1", Description="Squid")]
		Squid = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("798adef4-b02a-402d-b4a9-95413e8831cb", Description="Medium Schooling Fish")]
		MediumSchoolingFish = 30,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("720884ae-2ebe-498e-9e19-37612ff3c503", Description="Hake")]
		Hake = 31,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("34f641d6-8426-4e36-80ad-d53b4b7b9907", Description="Cod")]
		Cod = 32,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("2f64c23f-0b86-438c-a325-89e9c2b0d021", Description="Haddock")]
		Haddock = 33,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("657a88d8-cf56-48b2-8bdd-94eb051f52ed", Description="Mackerel")]
		Mackerel = 34,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("8630e5eb-3467-4844-8873-571108c115c6", Description="Large Schooling Fish")]
		LargeSchoolingFish = 60,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("fc9ad4d2-357e-4777-b14b-5e10805f127e", Description="Tuna")]
		Tuna = 61,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0cbdb5f4-cd51-4983-ad51-467eb4524121", Description="Small Shark")]
		SmallShark = 90,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d2f52bc2-9cd9-47c4-a4f7-354cfa2b985b", Description="Dogfish Shark")]
		DogfishShark = 91,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("d391df9d-ff8e-4341-9062-083d85a56846", Description="Medium Shark")]
		MediumShark = 120,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("bbee6ae8-6b4d-4478-ad15-107c236c2f64", Description="Mako Shark")]
		MakoShark = 121,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("5388e247-0bca-4313-b542-c422d102dca0", Description="Hammerhead Shark")]
		HammerheadShark = 122,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("8ad8e3db-f31f-4c96-a1f7-a59bc9683f0d", Description="Large Shark")]
		LargeShark = 150,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("8592ecd5-e45b-4c3e-9455-a11d7c19e27a", Description="Great White Shark")]
		GreatWhiteShark = 151,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("8e6168af-bc14-4ab1-8e75-0e50edef2d07", Description="Tiger Shark")]
		TigerShark = 152,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e36e5850-9a4d-46c8-8896-f5cf74b79a99", Description="Blue Shark")]
		BlueShark = 153,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("8a966e6e-1ee7-445e-abe6-77e46ac53c86", Description="Whale Shark")]
		WhaleShark = 154,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("3d0613a5-44c7-471f-a1e5-c545b77ec269", Description="Skate")]
		Skate = 180,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("072ce109-909b-431c-935d-a00adbe5f0ef", Description="Stingray")]
		Stingray = 181,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("fd0873ce-103b-42a1-906d-ff051edba25a", Description="Eel")]
		Eel = 190,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e8cc5668-12a0-4cad-b5c3-a1cda0497742", Description="Marlin")]
		Marlin = 200,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("3da12eb0-4369-45b9-87df-93d03db3a1c5", Description="Swordfish")]
		Swordfish = 201,
	}
}
