//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(365, "Surveillance/Status", 2)]
	public enum SurveillanceOrStatus : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("052a69ee-3a51-4297-aa06-1065b16d4fa7", Description="No Information")]
		NoInformation = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("463f9824-3aa2-4d4d-936a-6d7d952b9d43", Description="Emergency/Loss of Communications")]
		EmergencyOrLossOfCommunications = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("472c532d-566c-4237-8cd5-49fbb8486b1d", Description="SPI")]
		SPI = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("65f87f17-5be7-483b-ab20-0eeb7370eb90", Description="ATCRBS Code Change")]
		ATCRBSCodeChange = 3,
	}
}
