//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(163, "Transmitter-Modulation Type System", 16)]
	public enum TransmitterModulationTypeSystem : ushort {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("18d2ee56-526a-11df-b500-080069138b88", Description="Other")]
		Other = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("18d3fda0-526a-11df-a825-080069138b88", Description="Generic Radio or Simple Intercom")]
		GenericRadioOrSimpleIntercom = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("18d50fb0-526a-11df-82e8-080069138b88", Description="HAVE QUICK")]
		HAVEQUICK = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("18d61d92-526a-11df-ade3-080069138b88", Description="HAVE QUICK II")]
		HAVEQUICKII = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("18d7253e-526a-11df-8eec-080069138b88", Description="HAVE QUICK IIA")]
		HAVEQUICKIIA = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("18d836b8-526a-11df-9347-080069138b88", Description="SINCGARS")]
		SINCGARS = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("18d94698-526a-11df-9801-080069138b88", Description="CCTT SINCGARS")]
		CCTTSINCGARS = 6,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("18da50ba-526a-11df-8d80-080069138b88", Description="EPLRS (Enhanced Position Location Reporting System)")]
		EPLRSEnhancedPositionLocationReportingSystem = 7,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("18db691e-526a-11df-9c9c-080069138b88", Description="JTIDS/MIDS")]
		JTIDSOrMIDS = 8,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9533a0c3-ddec-4d56-8e49-a401e830e6ed", Description="Link 11")]
		Link11 = 9,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("745b65a8-c4fa-46cc-86f3-e930fc6b3452", Description="Link 11B")]
		Link11B = 10,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("440b193d-ea42-49f0-a2bc-92aa22446b5a", Description="L-Band SATCOM")]
		LBandSATCOM = 11,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9f2e5080-d67c-45fc-8002-8a1480908e06", Description="Enhanced SINCGARS 7.3")]
		EnhancedSINCGARS7_3 = 12,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("57c7d375-d111-4989-a30c-1504b1ee2fb4", Description="Navigation Aid")]
		NavigationAid = 13,
	}
}
