//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(224, "Transfer Control-Transfer Type", 8)]
	public enum TransferControlTransferType : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1c13858a-526a-11df-8609-080069138b88", Description="Other")]
		Other = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1c149286-526a-11df-8178-080069138b88", Description="Push Transfer - Entity")]
		PushTransferEntity = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1c15a766-526a-11df-9369-080069138b88", Description="Automatic Pull Transfer - Entity")]
		AutomaticPullTransferEntity = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1c16c10a-526a-11df-a8cf-080069138b88", Description="Not Used")]
		NotUsed = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1c17cfa0-526a-11df-96aa-080069138b88", Description="Push Transfer - Environmental Process")]
		PushTransferEnvironmentalProcess = 4,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1c18e516-526a-11df-a7bd-080069138b88", Description="Automatic Pull Transfer - Environmental Process")]
		AutomaticPullTransferEnvironmentalProcess = 5,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1c19fc94-526a-11df-a4e7-080069138b88", Description="Not Used")]
		NotUsed_1 = 6,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1c1b0c38-526a-11df-b8f2-080069138b88", Description="Cancel Transfer")]
		CancelTransfer = 7,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("40d3c184-ca1b-4f61-98f8-06ab93c3570f", Description="Manual Pull Transfer - Entity")]
		ManualPullTransferEntity = 8,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("e951d291-8e38-40b1-a3a3-a351bbb5ab5d", Description="Manual Pull Transfer - Environmental Process")]
		ManualPullTransferEnvironmentalProcess = 9,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("1459a642-8f55-4340-9895-3b7d468adddc", Description="Remove Entity")]
		RemoveEntity = 10,
	}
}
