//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(366, "Turn Rate Source", 2)]
	public enum TurnRateSource : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ea3b8a04-4ba6-4324-a95f-e2f3041a26ee", Description="Compute Locally")]
		ComputeLocally = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("9625b436-5c21-4a4d-867e-719add9d937b", Description="Less Than 1-Degree Turn or Not Turning")]
		LessThan1DegreeTurnOrNotTurning = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("ceba0a5e-dbba-4392-91d3-62dcdd6697f4", Description="1-Degree or Greater Turn Rate")]
		_1DegreeOrGreaterTurnRate = 2,
	}
}
