//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(145, "UA-Acoustic Emitter System Function", 8)]
	public enum UAAcousticEmitterSystemFunction : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("186b23a2-526a-11df-ba7e-080069138b88", Description="Other")]
		Other = 0,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("186c359e-526a-11df-a3e2-080069138b88", Description="Platform search/detect/track")]
		PlatformSearchOrDetectOrTrack = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("186d4574-526a-11df-91d7-080069138b88", Description="Navigation")]
		Navigation = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("186e543c-526a-11df-97a7-080069138b88", Description="Mine hunting")]
		MineHunting = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("186f653e-526a-11df-a2a0-080069138b88", Description="Weapon search/detect/track/detect")]
		WeaponSearchOrDetectOrTrackOrDetect = 4,
	}
}
