//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//Copyright © 2010-2011, 2013-2021 by the Simulation Interoperability Standards Organization, Inc.
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//All rights reserved.
//
//Schema and API: SISO hereby grants a general, royalty-free license to copy, distribute, display, and
//make derivative works from this material, for all purposes, provided that any use of the material
//contains the following attribution: “Reprinted with permission from SISO Inc.” Should
//a reader require additional information, contact the SISO Inc. Board of Directors.
//
//Documentation: SISO hereby grants a general, royalty-free license to copy, distribute,
//display, and make derivative works from this material, for noncommercial purposes, provided that
//any use of the material contains the following attribution: “Reprinted with permission from SISO Inc.” 
//The material may not be used for a commercial purpose without express written
//permission from the SISO Inc Board of Directors.
//
//SISO Inc. Board of Directors
//7901 4th St N, Suite 300-4043
//St. Petersburg, FL 33702
//
namespace Invicta.Net.SisoRef010 {
	
	[Invicta.Net.SisoRef010.Attributes.SisoEnumerationAttribute(136, "Variants for Air Category 200 - Bird", 8)]
	public enum VariantsForAirCategory200Bird : byte {
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("f21f363b-d42f-4352-9be4-3243f853934b", Description="Bird with Fish")]
		BirdWithFish = 1,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("35cb2051-3475-449a-ace7-fafb92b4fe07", Description="V-Pattern Flock Shape")]
		VPatternFlockShape = 2,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("5d53a809-787d-4753-b30f-582be8a9768a", Description="Circular Flock Shape")]
		CircularFlockShape = 3,
		[Invicta.Net.SisoRef010.Attributes.SisoEnumerantAttribute("0546722c-0e83-4647-b8a5-b08d3e8ae022", Description="Irregular Flock Shape")]
		IrregularFlockShape = 4,
	}
}
